[info confFile.y] parse configuration from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1/mdtx1.conf
[notice utcache.c] -------------------------------------------------------
[notice utcache.c] Paths
[notice utcache.c] .......................................................
[notice utcache.c] finalSupply input /path/to/file -> /path/to/file
[notice utcache.c] finalSupply output /path/to/file -> file
[notice utcache.c] finalSupply input /path/to/file: -> /path/to/file
[notice utcache.c] finalSupply output /path/to/file: -> file
[notice utcache.c] finalSupply input /path/to/file:place/to/strore/newFilename -> /path/to/file
[notice utcache.c] finalSupply output /path/to/file:place/to/strore/newFilename -> place/to/strore/newFilename
[notice utcache.c] finalSupply input /path/to/file:place/to/strore/newDirectory/ -> /path/to/file
[notice utcache.c] finalSupply output /path/to/file:place/to/strore/newDirectory/ -> place/to/strore/newDirectory/file
[notice utcache.c] -------------------------------------------------------
[notice utcache.c] Clean the cache:
[notice utcache.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll1/*
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll1 collection ( SX )
[info serverFile.y] parse coll1 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll1/servers.txt
[info extractFile.y] parse coll1 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll1/extract000.txt
[info openClose.c] steps: 93 / 93
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll2/*
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll2 collection ( SX )
[info serverFile.y] parse coll2 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll2/servers.txt
[info extractFile.y] parse coll2 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll2/extract000.txt
[info openClose.c] steps: 93 / 93
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/*
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection ( SX )
[info serverFile.y] parse coll3 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll3/servers.txt
[info extractFile.y] parse coll3 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll3/extract000.txt
[info openClose.c] steps: 93 / 93
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[notice utcache.c] -------------------------------------------------------
[notice utcache.c] Scan the cache directory :
[notice utcache.c] .......................................................
[notice utFunc.c] copy logo.png to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logo.png
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] /bin/cp execution returns 0
[notice utFunc.c] copy logo.tgz to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logo.tgz
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] /bin/cp execution returns 0
[notice utFunc.c] copy logoP1.cat to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logoP1.cat
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] /bin/cp execution returns 0
[notice utFunc.c] copy logoP2.cat to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logoP2.cat
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] /bin/cp execution returns 0
[notice utFunc.c] copy logoP1.iso to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logoP1.iso
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] /bin/cp execution returns 0
[notice utFunc.c] copy logoP2.iso to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logoP2.iso
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] /bin/cp execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] parse records file: LOCALSTATEDIR/cache/mediatex/mdtx1/md5sums/mdtx1-coll3.md5
[notice openClose.c] no md5sums file: LOCALSTATEDIR/cache/mediatex/mdtx1/md5sums/mdtx1-coll3.md5
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info md5sum.c] 022a34b2f9b893fba5774237e1aa80ea quick md5sum computed on 24075 bytes
[info md5sum.c] 022a34b2f9b893fba5774237e1aa80ea  full md5sum computed on 24075 bytes
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> AVAILABLE
[info md5sum.c] 0387eee9820fa224525ff8b2e0dfa9be quick md5sum computed on 24546 bytes
[info md5sum.c] 0387eee9820fa224525ff8b2e0dfa9be  full md5sum computed on 24546 bytes
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : UNUSED -> TOKEEP
[info md5sum.c] 1a167d608e76a6a4a8b16d168580873c quick md5sum computed on 20480 bytes
[info md5sum.c] 1a167d608e76a6a4a8b16d168580873c  full md5sum computed on 20480 bytes
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : UNUSED -> AVAILABLE
[info md5sum.c] de5008799752552b7963a2670dc5eb18 quick md5sum computed on 391168 bytes
[info md5sum.c] de5008799752552b7963a2670dc5eb18  full md5sum computed on 391168 bytes
[info cacheTree.c] de5008799752552b7963a2670dc5eb18:391168 (score=10.00) : UNUSED -> AVAILABLE
[info md5sum.c] c0c055a0829982bd646e2fafff01aaa6 quick md5sum computed on 4066 bytes
[info md5sum.c] c0c055a0829982bd646e2fafff01aaa6  full md5sum computed on 4066 bytes
[info cacheTree.c] c0c055a0829982bd646e2fafff01aaa6:4066 (score= 3.75) : UNUSED -> TOKEEP
[info md5sum.c] 0a7ecd447ef2acb3b5c6e4c550e6636f quick md5sum computed on 374784 bytes
[info md5sum.c] 0a7ecd447ef2acb3b5c6e4c550e6636f  full md5sum computed on 374784 bytes
[info cacheTree.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 (score= 3.75) : UNUSED -> TOKEEP
[notice utcache.c] .......................................................
[notice utcache.c] Scan gives :
[notice utcache.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c] 	Collection	coll3               
[notice recordTree.c] 	Type		UNKNOWN
[notice recordTree.c] 	Server		746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c] 	DoCypher	FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 0387eee9820fa224525ff8b2e0dfa9be               24546 logo.tgz
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 0a7ecd447ef2acb3b5c6e4c550e6636f              374784 logoP2.iso
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 1a167d608e76a6a4a8b16d168580873c               20480 logoP1.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd c0c055a0829982bd646e2fafff01aaa6                4066 logoP2.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd de5008799752552b7963a2670dc5eb18              391168 logoP1.iso
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice utcache.c] -------------------------------------------------------
[notice utcache.c] -------------------------------------------------------
[notice utcache.c] Keep logoP1.iso and logoP2.iso:
[notice utcache.c] .......................................................
[info cacheTree.c] de5008799752552b7963a2670dc5eb18:391168 (score=10.00) : AVAILABLE -> TOKEEP
[info cacheTree.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 (score= 3.75) : TOKEEP -> TOKEEP
[notice utcache.c] .......................................................
[notice utcache.c] Now we have :
[notice utcache.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c] 	Collection	coll3               
[notice recordTree.c] 	Type		UNKNOWN
[notice recordTree.c] 	Server		746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c] 	DoCypher	FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 0387eee9820fa224525ff8b2e0dfa9be               24546 logo.tgz
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd 0a7ecd447ef2acb3b5c6e4c550e6636f              374784 logoP2.iso
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 1a167d608e76a6a4a8b16d168580873c               20480 logoP1.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd c0c055a0829982bd646e2fafff01aaa6                4066 logoP2.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd de5008799752552b7963a2670dc5eb18              391168 logoP1.iso
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice utcache.c] -------------------------------------------------------
[notice utcache.c] -------------------------------------------------------
[notice utcache.c] Ask for too much place :
[notice utcache.c] .......................................................
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used         839119
[info cache.c] = free      104018481
[info cache.c]   total     104857600
[info cache.c] - frozen       794564
[info cache.c] = avail     104063036
[info cache.c] need        104857600
[notice cache.c] coll3's cache have no more room available now
[info cache.c] fails add record into coll3 cache
[notice utcache.c] .......................................................
[notice utcache.c] reply : 0
[notice utcache.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c] 	Collection	coll3               
[notice recordTree.c] 	Type		UNKNOWN
[notice recordTree.c] 	Server		746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c] 	DoCypher	FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 0387eee9820fa224525ff8b2e0dfa9be               24546 logo.tgz
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd 0a7ecd447ef2acb3b5c6e4c550e6636f              374784 logoP2.iso
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 1a167d608e76a6a4a8b16d168580873c               20480 logoP1.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd c0c055a0829982bd646e2fafff01aaa6                4066 logoP2.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd de5008799752552b7963a2670dc5eb18              391168 logoP1.iso
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice utcache.c] -------------------------------------------------------
[notice utcache.c] -------------------------------------------------------
[notice utcache.c] Ask for little place so do not suppress anything :
[notice utcache.c] .......................................................
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used         839119
[info cache.c] = free      104018481
[info cache.c]   total     104857600
[info cache.c] - frozen       794564
[info cache.c] = avail     104063036
[info cache.c] need        104018481
[info cacheTree.c] aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:104018481 (score=-1.00) : UNUSED -> ALLOCATED
[notice utcache.c] .......................................................
[notice utcache.c] reply : 1
[notice utcache.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c] 	Collection	coll3               
[notice recordTree.c] 	Type		UNKNOWN
[notice recordTree.c] 	Server		746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c] 	DoCypher	FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 0387eee9820fa224525ff8b2e0dfa9be               24546 logo.tgz
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd 0a7ecd447ef2acb3b5c6e4c550e6636f              374784 logoP2.iso
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 1a167d608e76a6a4a8b16d168580873c               20480 logoP1.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa           104018481 *malloc
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd c0c055a0829982bd646e2fafff01aaa6                4066 logoP2.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd de5008799752552b7963a2670dc5eb18              391168 logoP1.iso
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice utcache.c] -------------------------------------------------------
[info cacheTree.c] aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:104018481 (score=-1.00) : ALLOCATED -> UNUSED
[notice utcache.c] -------------------------------------------------------
[notice utcache.c] Ask for place so as we need to suppress files :
[notice utcache.c] .......................................................
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used         839119
[info cache.c] = free      104018481
[info cache.c]   total     104857600
[info cache.c] - frozen       794564
[info cache.c] = avail     104063036
[info cache.c] need        104063036
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : AVAILABLE -> AVAILABLE
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : AVAILABLE -> UNUSED
[notice cache.c] unlink LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.png
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : TOKEEP -> TOKEEP
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : AVAILABLE -> AVAILABLE
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : AVAILABLE -> UNUSED
[notice cache.c] unlink LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logoP1.cat
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used         794564
[info cache.c] = free      104063036
[info cache.c]   total     104857600
[info cache.c] - frozen       794564
[info cache.c] = avail     104063036
[info cacheTree.c] bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb:104063036 (score=-1.00) : UNUSED -> ALLOCATED
[info cacheTree.c] bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb:104063036 (score=-1.00) : ALLOCATED -> UNUSED
[notice utcache.c] .......................................................
[notice utcache.c] reply : 1
[notice utcache.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c] 	Collection	coll3               
[notice recordTree.c] 	Type		UNKNOWN
[notice recordTree.c] 	Server		746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c] 	DoCypher	FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 0387eee9820fa224525ff8b2e0dfa9be               24546 logo.tgz
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd 0a7ecd447ef2acb3b5c6e4c550e6636f              374784 logoP2.iso
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd c0c055a0829982bd646e2fafff01aaa6                4066 logoP2.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd de5008799752552b7963a2670dc5eb18              391168 logoP1.iso
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice utcache.c] -------------------------------------------------------
[notice utcache.c] -------------------------------------------------------
[notice utcache.c] Clean the cache:
[notice utcache.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll2/*
[info command.c] /bin/bash execution returns 0
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : TOKEEP -> UNUSED
[info cacheTree.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 (score= 3.75) : TOKEEP -> UNUSED
[info cacheTree.c] c0c055a0829982bd646e2fafff01aaa6:4066 (score= 3.75) : TOKEEP -> UNUSED
[info cacheTree.c] de5008799752552b7963a2670dc5eb18:391168 (score=10.00) : TOKEEP -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/*
[info command.c] /bin/bash execution returns 0
[info confTree.c] free configuration
[info utcache.c] exit on success
