[info confFile.y] parse configuration from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1/mdtx1.conf
[notice utFunc.c] ask for logo.png
[notice utFunc.c] add a generic demand for
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] Clean the cache:
[notice utcgiSrv.c] ..........................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] /bin/bash execution returns 0
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] 1) try to extract the demand
[notice utcgiSrv.c] ..........................................................
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] load coll3 records
[notice openClose.c] no md5sums file: LOCALSTATEDIR/cache/mediatex/mdtx1/md5sums/mdtx1-coll3.md5
[info serverFile.y] parse coll3 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll3/servers.txt
[info extractFile.y] parse coll3 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll3/extract000.txt
[info openClose.c] steps: 93 / 93
[notice extract.c] de5008799752552b7963a2670dc5eb18:391168 not found
[info extract.c] not found container ISO/de5008799752552b7963a2670dc5eb18:391168
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 not found
[notice extract.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 not found
[info extract.c] not found container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 not found
[info extract.c] not found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 not found
[info extract.c] not found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[notice extract.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 not found
[info extract.c] not found container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045
[notice extract.c] 65f1464142f405dbbeeea4830c95ddd3:25600 not found
[info extract.c] not found container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600
[notice extract.c] f54fba7d2e070d48051ac3f8f1c2eb98:30720 not found
[info extract.c] not found container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720
[notice extract.c] 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 not found
[info extract.c] not found container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457
[notice extract.c] fa2b0b536bf61f61617528c474e0bf61:24973 not found
[info extract.c] not found container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973
[notice extract.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 not found
[info extract.c] not found container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088
[notice extract.c] d79581b67ec1932fd276dcf3b6d6db9a:24733 not found
[info extract.c] not found container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733
[notice extract.c] 7808473c7db9a9e3493a6b61f44f8805:20480 not found
[notice extract.c] db8b80896f7202b656913f99d438075c:4090 not found
[info extract.c] not found container RAR/7808473c7db9a9e3493a6b61f44f8805:20480
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 not found
[notice cgiSrv.c] 303 not found 022a34b2f9b893fba5774237e1aa80ea:24075
[notice utcgiSrv.c] ..........................................................
[notice utcgiSrv.c] Now we have :
[notice utcgiSrv.c] ..........................................................
[info recordTree.c] Serializing UNKNOWN record tree in file: stdout
# Collection's records:
Headers
	Collection	coll3               
	Type		UNKNOWN
	Server		bedac32422739d7eced624ba20f5912e
	DoCypher	FALSE       
Body          
#                date                             host                             hash                size extra
              
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] 2) retry with it on cache
[notice utcgiSrv.c] ..........................................................
[notice utFunc.c] copy logo.png to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logo.png
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] /bin/cp execution returns 0
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info md5sum.c] 022a34b2f9b893fba5774237e1aa80ea quick md5sum computed on 24075 bytes
[info md5sum.c] 022a34b2f9b893fba5774237e1aa80ea  full md5sum computed on 24075 bytes
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection ( SX )
[info openClose.c] steps: 0 / 93
[warning extractScore.c] forgotten incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info cacheTree.c] archive status 022a34b2f9b893fba5774237e1aa80ea24075: UNUSED -> AVAILABLE
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info cacheTree.c] archive status 022a34b2f9b893fba5774237e1aa80ea24075: AVAILABLE -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[notice cgiSrv.c] 200 ok https://localhost/~mdtx1-coll3/cache/logo.png
[notice utcgiSrv.c] ..........................................................
[notice utcgiSrv.c] Now we have :
[notice utcgiSrv.c] ..........................................................
[info recordTree.c] Serializing UNKNOWN record tree in file: stdout
# Collection's records:
Headers
	Collection	coll3               
	Type		UNKNOWN
	Server		bedac32422739d7eced624ba20f5912e
	DoCypher	FALSE       
Body          
#                date                             host                             hash                size extra
S 2010-01-01,01:05:00 bedac32422739d7eced624ba20f5912e 022a34b2f9b893fba5774237e1aa80ea               24075 logo.png
# ^ LOCAL_SUPPLY
        
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] 3) retry with tgz on cache
[notice utcgiSrv.c] ..........................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] /bin/bash execution returns 0
[info cacheTree.c] archive status 022a34b2f9b893fba5774237e1aa80ea24075: TOKEEP -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] /bin/bash execution returns 0
[notice utFunc.c] copy logo.tgz to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logo.tgz
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] /bin/cp execution returns 0
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info md5sum.c] 0387eee9820fa224525ff8b2e0dfa9be quick md5sum computed on 24546 bytes
[info md5sum.c] 0387eee9820fa224525ff8b2e0dfa9be  full md5sum computed on 24546 bytes
[info cacheTree.c] archive status 0387eee9820fa224525ff8b2e0dfa9be24546: UNUSED -> TOKEEP
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info cacheTree.c] archive status 0387eee9820fa224525ff8b2e0dfa9be24546: TOKEEP -> TOKEEP
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 found
[info extract.c] found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          24546
[info cache.c] = free      104833054
[info cache.c]   total     104857600
[info cache.c] - frozen        24546
[info cache.c] = avail     104833054
[info cache.c] need            24075
[info cacheTree.c] archive status 022a34b2f9b893fba5774237e1aa80ea24075: UNUSED -> ALLOCATED
[notice extract.c] do tar -zxf
[info command.c] execScript: /bin/tar
[info command.c]  arg1: -C
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3
[info command.c]  arg3: -zxf
[info command.c]  arg4: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.tgz
[info command.c]  arg5: logo/logo.png
[info command.c] /bin/tar execution returns 0
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[info cacheTree.c] archive status 022a34b2f9b893fba5774237e1aa80ea24075: ALLOCATED -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 extracted
[info cache.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[info extract.c] del to-keep on 0387eee9820fa224525ff8b2e0dfa9be:24546
[info cacheTree.c] archive status 0387eee9820fa224525ff8b2e0dfa9be24546: TOKEEP -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[notice cgiSrv.c] 200 ok https://localhost/~mdtx1-coll3/cache/logo/logo.png
[notice utcgiSrv.c] ..........................................................
[notice utcgiSrv.c] Now we have :
[notice utcgiSrv.c] ..........................................................
[info recordTree.c] Serializing UNKNOWN record tree in file: stdout
# Collection's records:
Headers
	Collection	coll3               
	Type		UNKNOWN
	Server		bedac32422739d7eced624ba20f5912e
	DoCypher	FALSE       
Body          
#                date                             host                             hash                size extra
S 2010-01-01,01:05:00 bedac32422739d7eced624ba20f5912e 022a34b2f9b893fba5774237e1aa80ea               24075 logo/logo.png
# ^ LOCAL_SUPPLY
S 2010-01-01,01:00:00 bedac32422739d7eced624ba20f5912e 0387eee9820fa224525ff8b2e0dfa9be               24546 logo.tgz
# ^ LOCAL_SUPPLY
             
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] 4) try with only part1 on cache
[notice utcgiSrv.c] ..........................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] /bin/bash execution returns 0
[info cacheTree.c] archive status 022a34b2f9b893fba5774237e1aa80ea24075: TOKEEP -> UNUSED
[info cacheTree.c] archive status 0387eee9820fa224525ff8b2e0dfa9be24546: TOKEEP -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] /bin/bash execution returns 0
[notice utFunc.c] copy logoP1.cat to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logoP1.cat
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] /bin/cp execution returns 0
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info md5sum.c] 1a167d608e76a6a4a8b16d168580873c quick md5sum computed on 20480 bytes
[info md5sum.c] 1a167d608e76a6a4a8b16d168580873c  full md5sum computed on 20480 bytes
[info cacheTree.c] archive status 1a167d608e76a6a4a8b16d168580873c20480: UNUSED -> AVAILABLE
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info cacheTree.c] archive status 1a167d608e76a6a4a8b16d168580873c20480: AVAILABLE -> TOKEEP
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 found
[notice extract.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 not found
[info extract.c] not found container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 not found
[info extract.c] not found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[info extract.c] del to-keep on 1a167d608e76a6a4a8b16d168580873c:20480
[info cacheTree.c] archive status 1a167d608e76a6a4a8b16d168580873c20480: TOKEEP -> AVAILABLE
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 not found
[info extract.c] not found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[notice extract.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 not found
[info extract.c] not found container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045
[notice extract.c] 65f1464142f405dbbeeea4830c95ddd3:25600 not found
[info extract.c] not found container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600
[notice extract.c] f54fba7d2e070d48051ac3f8f1c2eb98:30720 not found
[info extract.c] not found container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720
[notice extract.c] 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 not found
[info extract.c] not found container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457
[notice extract.c] fa2b0b536bf61f61617528c474e0bf61:24973 not found
[info extract.c] not found container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973
[notice extract.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 not found
[info extract.c] not found container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088
[notice extract.c] d79581b67ec1932fd276dcf3b6d6db9a:24733 not found
[info extract.c] not found container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733
[notice extract.c] 7808473c7db9a9e3493a6b61f44f8805:20480 not found
[notice extract.c] db8b80896f7202b656913f99d438075c:4090 not found
[info extract.c] not found container RAR/7808473c7db9a9e3493a6b61f44f8805:20480
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 not found
[notice cgiSrv.c] 303 not found 022a34b2f9b893fba5774237e1aa80ea:24075
[notice utcgiSrv.c] ..........................................................
[notice utcgiSrv.c] Now we have :
[notice utcgiSrv.c] ..........................................................
[info recordTree.c] Serializing UNKNOWN record tree in file: stdout
# Collection's records:
Headers
	Collection	coll3               
	Type		UNKNOWN
	Server		bedac32422739d7eced624ba20f5912e
	DoCypher	FALSE       
Body          
#                date                             host                             hash                size extra
S 2010-01-01,01:00:00 bedac32422739d7eced624ba20f5912e 1a167d608e76a6a4a8b16d168580873c               20480 logoP1.cat
# ^ LOCAL_SUPPLY
      
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] 5) try with part2 added on cache too
[notice utcgiSrv.c] ..........................................................
[notice utFunc.c] copy logoP2.cat to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logoP2.cat
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] /bin/cp execution returns 0
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info md5sum.c] c0c055a0829982bd646e2fafff01aaa6 quick md5sum computed on 4066 bytes
[info md5sum.c] c0c055a0829982bd646e2fafff01aaa6  full md5sum computed on 4066 bytes
[info cacheTree.c] archive status c0c055a0829982bd646e2fafff01aaa64066: UNUSED -> TOKEEP
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info cacheTree.c] archive status 1a167d608e76a6a4a8b16d168580873c20480: AVAILABLE -> TOKEEP
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 found
[info cacheTree.c] archive status c0c055a0829982bd646e2fafff01aaa64066: TOKEEP -> TOKEEP
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 found
[info extract.c] found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          24546
[info cache.c] = free      104833054
[info cache.c]   total     104857600
[info cache.c] - frozen        24546
[info cache.c] = avail     104833054
[info cache.c] need            24546
[info cacheTree.c] archive status 0387eee9820fa224525ff8b2e0dfa9be24546: UNUSED -> ALLOCATED
[notice extract.c] do cat
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: /bin/cat LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logoP1.cat LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logoP2.cat >LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.tgz
[info command.c] /bin/bash execution returns 0
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.tgz to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.tgz
[info cacheTree.c] archive status 0387eee9820fa224525ff8b2e0dfa9be24546: ALLOCATED -> TOKEEP
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 extracted
[info extract.c] del to-keep on 1a167d608e76a6a4a8b16d168580873c:20480
[info cacheTree.c] archive status 1a167d608e76a6a4a8b16d168580873c20480: TOKEEP -> AVAILABLE
[info extract.c] del to-keep on c0c055a0829982bd646e2fafff01aaa6:4066
[info cacheTree.c] archive status c0c055a0829982bd646e2fafff01aaa64066: TOKEEP -> TOKEEP
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 found
[info extract.c] found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          49092
[info cache.c] = free      104808508
[info cache.c]   total     104857600
[info cache.c] - frozen        28612
[info cache.c] = avail     104828988
[info cache.c] need            24075
[info cacheTree.c] archive status 022a34b2f9b893fba5774237e1aa80ea24075: UNUSED -> ALLOCATED
[notice extract.c] do tar -zxf
[info command.c] execScript: /bin/tar
[info command.c]  arg1: -C
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3
[info command.c]  arg3: -zxf
[info command.c]  arg4: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.tgz
[info command.c]  arg5: logo/logo.png
[info command.c] /bin/tar execution returns 0
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[info cacheTree.c] archive status 022a34b2f9b893fba5774237e1aa80ea24075: ALLOCATED -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 extracted
[info cache.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[info extract.c] del to-keep on 0387eee9820fa224525ff8b2e0dfa9be:24546
[info cacheTree.c] archive status 0387eee9820fa224525ff8b2e0dfa9be24546: TOKEEP -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[notice cgiSrv.c] 200 ok https://localhost/~mdtx1-coll3/cache/logo/logo.png
[notice utcgiSrv.c] ..........................................................
[notice utcgiSrv.c] Now we have :
[notice utcgiSrv.c] ..........................................................
[info recordTree.c] Serializing UNKNOWN record tree in file: stdout
# Collection's records:
Headers
	Collection	coll3               
	Type		UNKNOWN
	Server		bedac32422739d7eced624ba20f5912e
	DoCypher	FALSE       
Body          
#                date                             host                             hash                size extra
S 2010-01-01,01:05:00 bedac32422739d7eced624ba20f5912e 022a34b2f9b893fba5774237e1aa80ea               24075 logo/logo.png
# ^ LOCAL_SUPPLY
S 2010-01-01,01:00:00 bedac32422739d7eced624ba20f5912e 0387eee9820fa224525ff8b2e0dfa9be               24546 logo.tgz
# ^ LOCAL_SUPPLY
S 2010-01-01,01:00:00 bedac32422739d7eced624ba20f5912e 1a167d608e76a6a4a8b16d168580873c               20480 logoP1.cat
# ^ LOCAL_SUPPLY
S 2010-01-01,01:00:00 bedac32422739d7eced624ba20f5912e c0c055a0829982bd646e2fafff01aaa6                4066 logoP2.cat
# ^ LOCAL_SUPPLY
             
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] 6) register a mail
[notice utcgiSrv.c] ..........................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] /bin/bash execution returns 0
[info cacheTree.c] archive status 022a34b2f9b893fba5774237e1aa80ea24075: TOKEEP -> UNUSED
[info cacheTree.c] archive status 0387eee9820fa224525ff8b2e0dfa9be24546: TOKEEP -> UNUSED
[info cacheTree.c] archive status 1a167d608e76a6a4a8b16d168580873c20480: AVAILABLE -> UNUSED
[info cacheTree.c] archive status c0c055a0829982bd646e2fafff01aaa64066: TOKEEP -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] /bin/bash execution returns 0
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[notice utFunc.c] ask for logo.png
[notice utFunc.c] add a generic demand for
[info cacheTree.c] archive status 022a34b2f9b893fba5774237e1aa80ea24075: UNUSED -> WANTED
[notice cgiSrv.c] 200 ok
[notice utcgiSrv.c] ..........................................................
[notice utcgiSrv.c] Now we have :
[notice utcgiSrv.c] ..........................................................
[info recordTree.c] Serializing UNKNOWN record tree in file: stdout
# Collection's records:
Headers
	Collection	coll3               
	Type		UNKNOWN
	Server		bedac32422739d7eced624ba20f5912e
	DoCypher	FALSE       
Body          
#                date                             host                             hash                size extra
D 2010-01-01,01:00:00 bedac32422739d7eced624ba20f5912e 022a34b2f9b893fba5774237e1aa80ea               24075 test@test.com
# ^ FINAL_DEMAND
   
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] ----------------------------------------------------------
[notice utcgiSrv.c] Clean the cache:
[notice utcgiSrv.c] ..........................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] /bin/bash execution returns 0
[info cacheTree.c] archive status 022a34b2f9b893fba5774237e1aa80ea24075: WANTED -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] /bin/bash execution returns 0
[info confTree.c] free configuration
[info utcgiSrv.c] exit on success
