[info confFile.y] parse configuration from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1/mdtx1.conf
[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] Clean the cache:
[notice utcgiSrv.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll1/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll1 collection ( SX )
[info serverFile.y] parse coll1 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll1/servers.txt
[info extractFile.y] parse coll1 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll1/extract000.txt
[info openClose.c] steps: 93 / 93
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll2/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll2 collection ( SX )
[info serverFile.y] parse coll2 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll2/servers.txt
[info extractFile.y] parse coll2 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll2/extract000.txt
[info openClose.c] steps: 93 / 93
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection ( SX )
[info serverFile.y] parse coll3 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll3/servers.txt
[info extractFile.y] parse coll3 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll3/extract000.txt
[info openClose.c] steps: 93 / 93
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] 1) try to extract the demand
[notice utcgiSrv.c] .......................................................
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] parse records file: LOCALSTATEDIR/cache/mediatex/mdtx1/md5sums/mdtx1-coll3.md5
[notice openClose.c] no md5sums file: LOCALSTATEDIR/cache/mediatex/mdtx1/md5sums/mdtx1-coll3.md5
[info openClose.c] steps: 0 / 93
[notice extract.c] de5008799752552b7963a2670dc5eb18:391168 not found
[info extract.c] not found container ISO/de5008799752552b7963a2670dc5eb18:391168
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 not found
[notice extract.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 not found
[info extract.c] not found container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 not found
[info extract.c] not found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 not found
[info extract.c] not found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[notice extract.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 not found
[info extract.c] not found container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045
[notice extract.c] 65f1464142f405dbbeeea4830c95ddd3:25600 not found
[info extract.c] not found container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600
[notice extract.c] f54fba7d2e070d48051ac3f8f1c2eb98:30720 not found
[info extract.c] not found container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720
[notice extract.c] 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 not found
[info extract.c] not found container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457
[notice extract.c] fa2b0b536bf61f61617528c474e0bf61:24973 not found
[info extract.c] not found container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973
[notice extract.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 not found
[info extract.c] not found container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088
[notice extract.c] d79581b67ec1932fd276dcf3b6d6db9a:24733 not found
[info extract.c] not found container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733
[notice extract.c] 7808473c7db9a9e3493a6b61f44f8805:20480 not found
[notice extract.c] db8b80896f7202b656913f99d438075c:4090 not found
[info extract.c] not found container RAR/7808473c7db9a9e3493a6b61f44f8805:20480
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 not found
[notice utcgiSrv.c] .......................................................
[notice utcgiSrv.c] Now we have :
[notice utcgiSrv.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] 2) retry with it on cache
[notice utcgiSrv.c] .......................................................
[notice utFunc.c] copy logo.png to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logo.png
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/cp execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info md5sum.c] 022a34b2f9b893fba5774237e1aa80ea quick md5sum computed on 24075 bytes
[info md5sum.c] 022a34b2f9b893fba5774237e1aa80ea  full md5sum computed on 24075 bytes
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> AVAILABLE
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : AVAILABLE -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[notice utcgiSrv.c] .......................................................
[notice utcgiSrv.c] Now we have :
[notice utcgiSrv.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] 3) retry with tgz on cache
[notice utcgiSrv.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll1/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll2/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[notice utFunc.c] copy logo.tgz to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logo.tgz
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/cp execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info md5sum.c] 0387eee9820fa224525ff8b2e0dfa9be quick md5sum computed on 24546 bytes
[info md5sum.c] 0387eee9820fa224525ff8b2e0dfa9be  full md5sum computed on 24546 bytes
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : UNUSED -> TOKEEP
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : TOKEEP -> TOKEEP
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 found
[info extract.c] found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          24546
[info cache.c] = free      104833054
[info cache.c]   total     104857600
[info cache.c] - frozen        24546
[info cache.c] = avail     104833054
[info cache.c] need            24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> ALLOCATED
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[notice extract.c] do tar -zxf
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar
[info command.c] execScript: /bin/tar
[info command.c]  arg1: -C
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar/
[info command.c]  arg3: -zxf
[info command.c]  arg4: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.tgz
[info command.c]  arg5: logo/logo.png
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/tar execution returns 0
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar/logo
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : ALLOCATED -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 extracted
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[info extract.c] del to-keep on 0387eee9820fa224525ff8b2e0dfa9be:24546
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : TOKEEP -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[notice utcgiSrv.c] .......................................................
[notice utcgiSrv.c] Now we have :
[notice utcgiSrv.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo/logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 0387eee9820fa224525ff8b2e0dfa9be               24546 logo.tgz
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] 4) try with only part1 on cache
[notice utcgiSrv.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll1/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll2/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> UNUSED
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : TOKEEP -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[notice utFunc.c] copy logoP1.cat to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logoP1.cat
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/cp execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info md5sum.c] 1a167d608e76a6a4a8b16d168580873c quick md5sum computed on 20480 bytes
[info md5sum.c] 1a167d608e76a6a4a8b16d168580873c  full md5sum computed on 20480 bytes
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : UNUSED -> AVAILABLE
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : AVAILABLE -> TOKEEP
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 found
[notice extract.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 not found
[info extract.c] not found container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 not found
[info extract.c] not found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[info extract.c] del to-keep on 1a167d608e76a6a4a8b16d168580873c:20480
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : TOKEEP -> AVAILABLE
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 not found
[info extract.c] not found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[notice extract.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 not found
[info extract.c] not found container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045
[notice extract.c] 65f1464142f405dbbeeea4830c95ddd3:25600 not found
[info extract.c] not found container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600
[notice extract.c] f54fba7d2e070d48051ac3f8f1c2eb98:30720 not found
[info extract.c] not found container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720
[notice extract.c] 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 not found
[info extract.c] not found container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457
[notice extract.c] fa2b0b536bf61f61617528c474e0bf61:24973 not found
[info extract.c] not found container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973
[notice extract.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 not found
[info extract.c] not found container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088
[notice extract.c] d79581b67ec1932fd276dcf3b6d6db9a:24733 not found
[info extract.c] not found container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733
[notice extract.c] 7808473c7db9a9e3493a6b61f44f8805:20480 not found
[notice extract.c] db8b80896f7202b656913f99d438075c:4090 not found
[info extract.c] not found container RAR/7808473c7db9a9e3493a6b61f44f8805:20480
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 not found
[notice utcgiSrv.c] .......................................................
[notice utcgiSrv.c] Now we have :
[notice utcgiSrv.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 1a167d608e76a6a4a8b16d168580873c               20480 logoP1.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] 5) try with part2 added on cache too
[notice utcgiSrv.c] .......................................................
[notice utFunc.c] copy logoP2.cat to the coll3 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logoP2.cat
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/cp execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info cache.c] logoP1.cat match: md5sum skipped
[info md5sum.c] c0c055a0829982bd646e2fafff01aaa6 quick md5sum computed on 4066 bytes
[info md5sum.c] c0c055a0829982bd646e2fafff01aaa6  full md5sum computed on 4066 bytes
[info cacheTree.c] c0c055a0829982bd646e2fafff01aaa6:4066 (score= 3.75) : UNUSED -> TOKEEP
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : AVAILABLE -> TOKEEP
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 found
[info cacheTree.c] c0c055a0829982bd646e2fafff01aaa6:4066 (score= 3.75) : TOKEEP -> TOKEEP
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 found
[info extract.c] found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          24546
[info cache.c] = free      104833054
[info cache.c]   total     104857600
[info cache.c] - frozen        24546
[info cache.c] = avail     104833054
[info cache.c] need            24546
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : UNUSED -> ALLOCATED
[notice extract.c] do cat
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: /bin/cat LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logoP1.cat LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logoP2.cat >LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.tgz
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.tgz to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.tgz
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : ALLOCATED -> TOKEEP
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 extracted
[info extract.c] del to-keep on 1a167d608e76a6a4a8b16d168580873c:20480
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : TOKEEP -> AVAILABLE
[info extract.c] del to-keep on c0c055a0829982bd646e2fafff01aaa6:4066
[info cacheTree.c] c0c055a0829982bd646e2fafff01aaa6:4066 (score= 3.75) : TOKEEP -> TOKEEP
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 found
[info extract.c] found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          49092
[info cache.c] = free      104808508
[info cache.c]   total     104857600
[info cache.c] - frozen        28612
[info cache.c] = avail     104828988
[info cache.c] need            24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> ALLOCATED
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[notice extract.c] do tar -zxf
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar
[info command.c] execScript: /bin/tar
[info command.c]  arg1: -C
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar/
[info command.c]  arg3: -zxf
[info command.c]  arg4: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.tgz
[info command.c]  arg5: logo/logo.png
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/tar execution returns 0
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar/logo
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : ALLOCATED -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 extracted
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[info extract.c] del to-keep on 0387eee9820fa224525ff8b2e0dfa9be:24546
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : TOKEEP -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[notice utcgiSrv.c] .......................................................
[notice utcgiSrv.c] Now we have :
[notice utcgiSrv.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo/logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 0387eee9820fa224525ff8b2e0dfa9be               24546 logo.tgz
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 1a167d608e76a6a4a8b16d168580873c               20480 logoP1.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd c0c055a0829982bd646e2fafff01aaa6                4066 logoP2.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] 6) register a mail
[notice utcgiSrv.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll1/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll2/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> UNUSED
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : TOKEEP -> UNUSED
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : AVAILABLE -> UNUSED
[info cacheTree.c] c0c055a0829982bd646e2fafff01aaa6:4066 (score= 3.75) : TOKEEP -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> WANTED
[notice utcgiSrv.c] .......................................................
[notice utcgiSrv.c] Now we have :
[notice utcgiSrv.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] D 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 test@test.com
[notice recordTree.c] # ^ FINAL_DEMAND

[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] -------------------------------------------------------
[notice utcgiSrv.c] Clean the cache:
[notice utcgiSrv.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll1/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll2/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : WANTED -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/*
[info command.c] close stdout from child (use '-sinfo:debug' to undo)
[info command.c] /bin/bash execution returns 0
[info confTree.c] free configuration
[info utcgiSrv.c] exit on success
