[info confFile.y] parse configuration from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1/mdtx1.conf
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] Clean the cache:
[notice utextract.c] .......................................................
[notice utFunc.c] clean cache for all collections
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] add a demand for logo.png:
[notice utextract.c] .......................................................
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> WANTED
[notice utextract.c] .......................................................
[notice utextract.c] Now we have :
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] D 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 test@test.com
[notice recordTree.c] # ^ FINAL_DEMAND
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] try to extract the demand (1)
[notice utextract.c] .......................................................
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info extract.c] looking for 022a34b2f9b893fba5774237e1aa80ea24075
[notice extract.c] de5008799752552b7963a2670dc5eb18:391168 not found
[info extract.c] not found container ISO/de5008799752552b7963a2670dc5eb18:391168
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 not found
[notice extract.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 not found
[info extract.c] not found container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 not found
[info extract.c] not found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 not found
[info extract.c] not found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[notice extract.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 not found
[info extract.c] not found container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045
[notice extract.c] 65f1464142f405dbbeeea4830c95ddd3:25600 not found
[info extract.c] not found container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600
[notice extract.c] f54fba7d2e070d48051ac3f8f1c2eb98:30720 not found
[info extract.c] not found container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720
[notice extract.c] 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 not found
[info extract.c] not found container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457
[notice extract.c] fa2b0b536bf61f61617528c474e0bf61:24973 not found
[info extract.c] not found container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973
[notice extract.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 not found
[info extract.c] not found container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088
[notice extract.c] d79581b67ec1932fd276dcf3b6d6db9a:24733 not found
[info extract.c] not found container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733
[notice extract.c] 7808473c7db9a9e3493a6b61f44f8805:20480 not found
[notice extract.c] db8b80896f7202b656913f99d438075c:4090 not found
[info extract.c] not found container RAR/7808473c7db9a9e3493a6b61f44f8805:20480
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 not found
[notice utextract.c] .......................................................
[notice utextract.c] Now we have :
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] D 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 test@test.com
[notice recordTree.c] # ^ FINAL_DEMAND
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] Put containers files:
[notice utextract.c] .......................................................
[notice utFunc.c] copy logoP1.cat into the coll3 cache
[notice utFunc.c] copy logoP2.cat into the coll3 cache
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info cache.c] scan: logoP1.cat
[info md5sum.c] 1a167d608e76a6a4a8b16d168580873c quick md5sum computed on 20480 bytes
[info md5sum.c] 1a167d608e76a6a4a8b16d168580873c  full md5sum computed on 20480 bytes
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : UNUSED -> AVAILABLE
[info cache.c] scan: logoP2.cat
[info md5sum.c] c0c055a0829982bd646e2fafff01aaa6 quick md5sum computed on 4066 bytes
[info md5sum.c] c0c055a0829982bd646e2fafff01aaa6  full md5sum computed on 4066 bytes
[info cacheTree.c] c0c055a0829982bd646e2fafff01aaa6:4066 (score= 3.75) : UNUSED -> TOKEEP
[notice utextract.c] .......................................................
[notice utextract.c] Scan gives :
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] D 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 test@test.com
[notice recordTree.c] # ^ FINAL_DEMAND
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 1a167d608e76a6a4a8b16d168580873c               20480 logoP1.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd c0c055a0829982bd646e2fafff01aaa6                4066 logoP2.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] try to extract the demand (2)
[notice utextract.c] .......................................................
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info extract.c] looking for 022a34b2f9b893fba5774237e1aa80ea24075
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : AVAILABLE -> TOKEEP
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 found
[info cacheTree.c] c0c055a0829982bd646e2fafff01aaa6:4066 (score= 3.75) : TOKEEP -> TOKEEP
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 found
[info extract.c] found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          24546
[info cache.c] = free      104833054
[info cache.c]   total     104857600
[info cache.c] - frozen        24546
[info cache.c] = avail     104833054
[info cache.c] need            24546
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : UNUSED -> ALLOCATED
[notice extract.c] do cat
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: /bin/cat LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logoP1.cat LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logoP2.cat >LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.tgz
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.tgz to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.tgz
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.tgz
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.tgz
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : ALLOCATED -> TOKEEP
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 extracted
[info extract.c] del to-keep on 1a167d608e76a6a4a8b16d168580873c:20480
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : TOKEEP -> AVAILABLE
[info extract.c] del to-keep on c0c055a0829982bd646e2fafff01aaa6:4066
[info cacheTree.c] c0c055a0829982bd646e2fafff01aaa6:4066 (score= 3.75) : TOKEEP -> TOKEEP
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 found
[info extract.c] found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          49092
[info cache.c] = free      104808508
[info cache.c]   total     104857600
[info cache.c] - frozen        28612
[info cache.c] = avail     104828988
[info cache.c] need            24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : WANTED -> ALLOCATED
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[notice extract.c] do tar -zxf
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar
[info command.c] execScript: /bin/tar
[info command.c]  arg1: -C
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar/
[info command.c]  arg3: -zxf
[info command.c]  arg4: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.tgz
[info command.c]  arg5: logo/logo.png
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/tar execution returns 0
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar/logo
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : ALLOCATED -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 extracted
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[info extract.c] del to-keep on 0387eee9820fa224525ff8b2e0dfa9be:24546
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : TOKEEP -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[info extract.c] del to-keep on 022a34b2f9b893fba5774237e1aa80ea:24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[notice utextract.c] .......................................................
[notice utextract.c] Now we have :
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-16,01:00:05 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo/logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 0387eee9820fa224525ff8b2e0dfa9be               24546 logo.tgz
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 1a167d608e76a6a4a8b16d168580873c               20480 logoP1.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd c0c055a0829982bd646e2fafff01aaa6                4066 logoP2.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] Try tar-bzip2 container:
[notice utextract.c] .......................................................
[notice utFunc.c] clean cache for all collections
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> WANTED
[notice utFunc.c] copy logo.tar.bz2 into the coll3 cache
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info cache.c] scan: logo.tar.bz2
[info md5sum.c] b5810aba99ed0d15f1f0a073e646d5bd quick md5sum computed on 25045 bytes
[info md5sum.c] b5810aba99ed0d15f1f0a073e646d5bd  full md5sum computed on 25045 bytes
[info cacheTree.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 (score= 0.00) : UNUSED -> TOKEEP
[notice utextract.c] .......................................................
[notice utextract.c] Scan before tar-bzip:
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] D 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 test@test.com
[notice recordTree.c] # ^ FINAL_DEMAND
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd b5810aba99ed0d15f1f0a073e646d5bd               25045 logo.tar.bz2
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice utextract.c] -------------------------------------------------------
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info extract.c] looking for 022a34b2f9b893fba5774237e1aa80ea24075
[notice extract.c] de5008799752552b7963a2670dc5eb18:391168 not found
[info extract.c] not found container ISO/de5008799752552b7963a2670dc5eb18:391168
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 not found
[notice extract.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 not found
[info extract.c] not found container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 not found
[info extract.c] not found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 not found
[info extract.c] not found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[info cacheTree.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 (score= 0.00) : TOKEEP -> TOKEEP
[notice extract.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 found
[info extract.c] found container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          25045
[info cache.c] = free      104832555
[info cache.c]   total     104857600
[info cache.c] - frozen        25045
[info cache.c] = avail     104832555
[info cache.c] need            24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : WANTED -> ALLOCATED
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[notice extract.c] do tar -jxf
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar
[info command.c] execScript: /bin/tar
[info command.c]  arg1: -C
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar/
[info command.c]  arg3: -jxf
[info command.c]  arg4: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.tar.bz2
[info command.c]  arg5: logo/logo.png
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/tar execution returns 0
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar/logo
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : ALLOCATED -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 extracted
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[info extract.c] del to-keep on b5810aba99ed0d15f1f0a073e646d5bd:25045
[info cacheTree.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 (score= 0.00) : TOKEEP -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[info extract.c] del to-keep on 022a34b2f9b893fba5774237e1aa80ea:24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[notice utextract.c] .......................................................
[notice utextract.c] Now we have :
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-16,01:00:05 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo/logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd b5810aba99ed0d15f1f0a073e646d5bd               25045 logo.tar.bz2
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] Try zip container:
[notice utextract.c] .......................................................
[notice utFunc.c] clean cache for all collections
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> WANTED
[notice utFunc.c] copy logo.zip into the coll3 cache
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info cache.c] scan: logo.zip
[info md5sum.c] d79581b67ec1932fd276dcf3b6d6db9a quick md5sum computed on 24733 bytes
[info md5sum.c] d79581b67ec1932fd276dcf3b6d6db9a  full md5sum computed on 24733 bytes
[info cacheTree.c] d79581b67ec1932fd276dcf3b6d6db9a:24733 (score= 0.00) : UNUSED -> TOKEEP
[notice utextract.c] .......................................................
[notice utextract.c] Scan before unzip:
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] D 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 test@test.com
[notice recordTree.c] # ^ FINAL_DEMAND
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd d79581b67ec1932fd276dcf3b6d6db9a               24733 logo.zip
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice utextract.c] -------------------------------------------------------
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info extract.c] looking for 022a34b2f9b893fba5774237e1aa80ea24075
[notice extract.c] de5008799752552b7963a2670dc5eb18:391168 not found
[info extract.c] not found container ISO/de5008799752552b7963a2670dc5eb18:391168
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 not found
[notice extract.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 not found
[info extract.c] not found container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 not found
[info extract.c] not found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 not found
[info extract.c] not found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[notice extract.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 not found
[info extract.c] not found container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045
[notice extract.c] 65f1464142f405dbbeeea4830c95ddd3:25600 not found
[info extract.c] not found container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600
[notice extract.c] f54fba7d2e070d48051ac3f8f1c2eb98:30720 not found
[info extract.c] not found container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720
[notice extract.c] 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 not found
[info extract.c] not found container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457
[notice extract.c] fa2b0b536bf61f61617528c474e0bf61:24973 not found
[info extract.c] not found container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973
[notice extract.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 not found
[info extract.c] not found container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088
[info cacheTree.c] d79581b67ec1932fd276dcf3b6d6db9a:24733 (score= 0.00) : TOKEEP -> TOKEEP
[notice extract.c] d79581b67ec1932fd276dcf3b6d6db9a:24733 found
[info extract.c] found container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          24733
[info cache.c] = free      104832867
[info cache.c]   total     104857600
[info cache.c] - frozen        24733
[info cache.c] = avail     104832867
[info cache.c] need            24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : WANTED -> ALLOCATED
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[notice extract.c] do unzip
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/zip
[info command.c] execScript: /usr/bin/unzip
[info command.c]  arg1: -d
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/zip/
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.zip
[info command.c]  arg4: logo/logo.png
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /usr/bin/unzip execution returns 0
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/zip/logo
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/zip
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : ALLOCATED -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 extracted
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[info extract.c] del to-keep on d79581b67ec1932fd276dcf3b6d6db9a:24733
[info cacheTree.c] d79581b67ec1932fd276dcf3b6d6db9a:24733 (score= 0.00) : TOKEEP -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[info extract.c] del to-keep on 022a34b2f9b893fba5774237e1aa80ea:24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[notice utextract.c] .......................................................
[notice utextract.c] Now we have :
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-16,01:00:05 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo/logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd d79581b67ec1932fd276dcf3b6d6db9a               24733 logo.zip
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] Try tar container:
[notice utextract.c] .......................................................
[notice utFunc.c] clean cache for all collections
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> WANTED
[notice utFunc.c] copy logo.tar into the coll3 cache
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info cache.c] scan: logo.tar
[info md5sum.c] f54fba7d2e070d48051ac3f8f1c2eb98 quick md5sum computed on 30720 bytes
[info md5sum.c] f54fba7d2e070d48051ac3f8f1c2eb98  full md5sum computed on 30720 bytes
[info cacheTree.c] f54fba7d2e070d48051ac3f8f1c2eb98:30720 (score= 0.00) : UNUSED -> TOKEEP
[notice utextract.c] .......................................................
[notice utextract.c] Scan before tar:
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] D 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 test@test.com
[notice recordTree.c] # ^ FINAL_DEMAND
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd f54fba7d2e070d48051ac3f8f1c2eb98               30720 logo.tar
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice utextract.c] -------------------------------------------------------
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info extract.c] looking for 022a34b2f9b893fba5774237e1aa80ea24075
[notice extract.c] de5008799752552b7963a2670dc5eb18:391168 not found
[info extract.c] not found container ISO/de5008799752552b7963a2670dc5eb18:391168
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 not found
[notice extract.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 not found
[info extract.c] not found container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 not found
[info extract.c] not found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 not found
[info extract.c] not found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[notice extract.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 not found
[info extract.c] not found container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045
[notice extract.c] 65f1464142f405dbbeeea4830c95ddd3:25600 not found
[info extract.c] not found container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600
[info cacheTree.c] f54fba7d2e070d48051ac3f8f1c2eb98:30720 (score= 0.00) : TOKEEP -> TOKEEP
[notice extract.c] f54fba7d2e070d48051ac3f8f1c2eb98:30720 found
[info extract.c] found container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          30720
[info cache.c] = free      104826880
[info cache.c]   total     104857600
[info cache.c] - frozen        30720
[info cache.c] = avail     104826880
[info cache.c] need            24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : WANTED -> ALLOCATED
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[notice extract.c] do tar -xf
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar
[info command.c] execScript: /bin/tar
[info command.c]  arg1: -C
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar/
[info command.c]  arg3: -xf
[info command.c]  arg4: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.tar
[info command.c]  arg5: logo/logo.png
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/tar execution returns 0
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar/logo
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/tar
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : ALLOCATED -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 extracted
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[info extract.c] del to-keep on f54fba7d2e070d48051ac3f8f1c2eb98:30720
[info cacheTree.c] f54fba7d2e070d48051ac3f8f1c2eb98:30720 (score= 0.00) : TOKEEP -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[info extract.c] del to-keep on 022a34b2f9b893fba5774237e1aa80ea:24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[notice utextract.c] .......................................................
[notice utextract.c] Now we have :
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-16,01:00:05 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo/logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd f54fba7d2e070d48051ac3f8f1c2eb98               30720 logo.tar
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] Try cpio+gz container:
[notice utextract.c] .......................................................
[notice utFunc.c] clean cache for all collections
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> WANTED
[notice utFunc.c] copy logo.cpio.gz into the coll3 cache
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info cache.c] scan: logo.cpio.gz
[info md5sum.c] 3a04277dd1f43740a5fe17fd0ae9a5aa quick md5sum computed on 24457 bytes
[info md5sum.c] 3a04277dd1f43740a5fe17fd0ae9a5aa  full md5sum computed on 24457 bytes
[info cacheTree.c] 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 (score= 0.00) : UNUSED -> TOKEEP
[notice utextract.c] .......................................................
[notice utextract.c] Scan before tar:
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] D 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 test@test.com
[notice recordTree.c] # ^ FINAL_DEMAND
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 3a04277dd1f43740a5fe17fd0ae9a5aa               24457 logo.cpio.gz
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice utextract.c] -------------------------------------------------------
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info extract.c] looking for 022a34b2f9b893fba5774237e1aa80ea24075
[notice extract.c] de5008799752552b7963a2670dc5eb18:391168 not found
[info extract.c] not found container ISO/de5008799752552b7963a2670dc5eb18:391168
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 not found
[notice extract.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 not found
[info extract.c] not found container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 not found
[info extract.c] not found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 not found
[info extract.c] not found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[notice extract.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 not found
[info extract.c] not found container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045
[notice extract.c] 65f1464142f405dbbeeea4830c95ddd3:25600 not found
[info extract.c] not found container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600
[notice extract.c] f54fba7d2e070d48051ac3f8f1c2eb98:30720 not found
[info extract.c] not found container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720
[info cacheTree.c] 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 (score= 0.00) : TOKEEP -> TOKEEP
[notice extract.c] 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 found
[info extract.c] found container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          24457
[info cache.c] = free      104833143
[info cache.c]   total     104857600
[info cache.c] - frozen        24457
[info cache.c] = avail     104833143
[info cache.c] need            25088
[info cacheTree.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 (score= 0.00) : UNUSED -> ALLOCATED
[notice extract.c] do /bin/zcat 
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: /bin/zcat LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.cpio.gz >LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.cpio
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.cpio to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.cpio
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.cpio
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.cpio
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info cacheTree.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 (score= 0.00) : ALLOCATED -> TOKEEP
[notice extract.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 extracted
[info extract.c] del to-keep on 3a04277dd1f43740a5fe17fd0ae9a5aa:24457
[info cacheTree.c] 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 (score= 0.00) : TOKEEP -> TOKEEP
[notice extract.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 found
[info extract.c] found container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          49545
[info cache.c] = free      104808055
[info cache.c]   total     104857600
[info cache.c] - frozen        49545
[info cache.c] = avail     104808055
[info cache.c] need            24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : WANTED -> ALLOCATED
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[notice extract.c] do cpio -i
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/cpio
[info command.c] execScript PWD=LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/cpio/ (no-stderr): /bin/cpio
[info command.c]  arg1: -i
[info command.c]  arg2: --file
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.cpio
[info command.c]  arg4: --make-directories
[info command.c]  arg5: logo/logo.png
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
49 blocs
[info command.c] --- exec system call end ---
[info command.c] /bin/cpio execution returns 0
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/cpio/logo
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/cpio
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : ALLOCATED -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 extracted
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[info extract.c] del to-keep on b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088
[info cacheTree.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 (score= 0.00) : TOKEEP -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[info extract.c] del to-keep on 022a34b2f9b893fba5774237e1aa80ea:24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[notice utextract.c] .......................................................
[notice utextract.c] Now we have :
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-16,01:00:05 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo/logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 3a04277dd1f43740a5fe17fd0ae9a5aa               24457 logo.cpio.gz
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5               25088 logo.cpio
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] Try cpio+bz2 container:
[notice utextract.c] .......................................................
[notice utFunc.c] clean cache for all collections
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> WANTED
[notice utFunc.c] copy logo.cpio.bz2 into the coll3 cache
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[info cache.c] scan: logo.cpio.bz2
[info md5sum.c] fa2b0b536bf61f61617528c474e0bf61 quick md5sum computed on 24973 bytes
[info md5sum.c] fa2b0b536bf61f61617528c474e0bf61  full md5sum computed on 24973 bytes
[info cacheTree.c] fa2b0b536bf61f61617528c474e0bf61:24973 (score= 0.00) : UNUSED -> TOKEEP
[notice utextract.c] .......................................................
[notice utextract.c] Scan before tar:
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] D 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 test@test.com
[notice recordTree.c] # ^ FINAL_DEMAND
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd fa2b0b536bf61f61617528c474e0bf61               24973 logo.cpio.bz2
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice utextract.c] -------------------------------------------------------
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5SX )
[info openClose.c] steps: 0 / 93
[info extract.c] looking for 022a34b2f9b893fba5774237e1aa80ea24075
[notice extract.c] de5008799752552b7963a2670dc5eb18:391168 not found
[info extract.c] not found container ISO/de5008799752552b7963a2670dc5eb18:391168
[notice extract.c] 1a167d608e76a6a4a8b16d168580873c:20480 not found
[notice extract.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 not found
[info extract.c] not found container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[notice extract.c] c0c055a0829982bd646e2fafff01aaa6:4066 not found
[info extract.c] not found container CAT/1a167d608e76a6a4a8b16d168580873c:20480
[notice extract.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 not found
[info extract.c] not found container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[notice extract.c] b5810aba99ed0d15f1f0a073e646d5bd:25045 not found
[info extract.c] not found container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045
[notice extract.c] 65f1464142f405dbbeeea4830c95ddd3:25600 not found
[info extract.c] not found container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600
[notice extract.c] f54fba7d2e070d48051ac3f8f1c2eb98:30720 not found
[info extract.c] not found container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720
[notice extract.c] 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 not found
[info extract.c] not found container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457
[info cacheTree.c] fa2b0b536bf61f61617528c474e0bf61:24973 (score= 0.00) : TOKEEP -> TOKEEP
[notice extract.c] fa2b0b536bf61f61617528c474e0bf61:24973 found
[info extract.c] found container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          24973
[info cache.c] = free      104832627
[info cache.c]   total     104857600
[info cache.c] - frozen        24973
[info cache.c] = avail     104832627
[info cache.c] need            25088
[info cacheTree.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 (score= 0.00) : UNUSED -> ALLOCATED
[notice extract.c] do /bin/bzcat 
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: /bin/bzcat LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.cpio.bz2 >LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.cpio
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.cpio to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.cpio
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo.cpio
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.cpio
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info cacheTree.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 (score= 0.00) : ALLOCATED -> TOKEEP
[notice extract.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 extracted
[info extract.c] del to-keep on fa2b0b536bf61f61617528c474e0bf61:24973
[info cacheTree.c] fa2b0b536bf61f61617528c474e0bf61:24973 (score= 0.00) : TOKEEP -> TOKEEP
[notice extract.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 found
[info extract.c] found container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used          50061
[info cache.c] = free      104807539
[info cache.c]   total     104857600
[info cache.c] - frozen        50061
[info cache.c] = avail     104807539
[info cache.c] need            24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : WANTED -> ALLOCATED
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[notice extract.c] do cpio -i
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/cpio
[info command.c] execScript PWD=LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/cpio/ (no-stderr): /bin/cpio
[info command.c]  arg1: -i
[info command.c]  arg2: --file
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo.cpio
[info command.c]  arg4: --make-directories
[info command.c]  arg5: logo/logo.png
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
49 blocs
[info command.c] --- exec system call end ---
[info command.c] /bin/cpio execution returns 0
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/cpio/logo
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/cpio
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo/logo.png
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/logo/logo.png
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : ALLOCATED -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 extracted
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/logo
[info extract.c] del to-keep on b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088
[info cacheTree.c] b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 (score= 0.00) : TOKEEP -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[info extract.c] del to-keep on 022a34b2f9b893fba5774237e1aa80ea:24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[notice utextract.c] .......................................................
[notice utextract.c] Now we have :
[notice utextract.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-16,01:00:05 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 logo/logo.png
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5               25088 logo.cpio
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice recordTree.c] S 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd fa2b0b536bf61f61617528c474e0bf61               24973 logo.cpio.bz2
[notice recordTree.c] # ^ LOCAL_SUPPLY
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] -------------------------------------------------------
[notice utextract.c] Clean the cache:
[notice utextract.c] .......................................................
[notice utFunc.c] clean cache for all collections
[info confTree.c] free configuration
[info utextract.c] exit on success
