[info confFile.y] parse configuration from LOCALSTATEDIR/cache/mediatex/mdtx2/cvs/mdtx2/mdtx2.conf
[notice utnotify.c] -------------------------------------------------------
[notice utnotify.c] Clean the cache:
[notice utnotify.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/tmp/mdtx2-coll1/*
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll1 collection ( SX )
[info serverFile.y] parse coll1 servers from LOCALSTATEDIR/cache/mediatex/mdtx2/cvs/mdtx2-coll1/servers.txt
[info extractFile.y] parse coll1 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx2/cvs/mdtx2-coll1/extract000.txt
[info openClose.c] steps: 93 / 93
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll2/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/tmp/mdtx2-coll2/*
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll2 collection ( SX )
[info serverFile.y] parse coll2 servers from LOCALSTATEDIR/cache/mediatex/mdtx2/cvs/mdtx2-coll2/servers.txt
[info extractFile.y] parse coll2 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx2/cvs/mdtx2-coll2/extract000.txt
[info openClose.c] steps: 93 / 93
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll3/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/tmp/mdtx2-coll3/*
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection ( SX )
[info serverFile.y] parse coll3 servers from LOCALSTATEDIR/cache/mediatex/mdtx2/cvs/mdtx2-coll3/servers.txt
[info extractFile.y] parse coll3 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx2/cvs/mdtx2-coll3/extract000.txt
[info openClose.c] steps: 93 / 93
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[notice utnotify.c] localhost is 6b18ed0194b0fbadd08e0a13cccda00e
[notice utnotify.c] -------------------------------------------------------
[notice utnotify.c] *** test sending message:
[notice utnotify.c] .......................................................
[notice utnotify.c] -------------------------------------------------------
[notice utnotify.c] Populate the cache:
[notice utnotify.c] .......................................................
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> WANTED
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : WANTED -> WANTED
[notice utFunc.c] copy logoP1.cat to the coll1 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logoP1.cat
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll1
[info command.c] /bin/cp execution returns 0
[notice utFunc.c] copy logo.tgz to the coll1 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logo.tgz
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll1
[info command.c] /bin/cp execution returns 0
[notice utFunc.c] copy logoP2.iso to the coll1 cache
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: ./../misc/logoP2.iso
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll1
[info command.c] /bin/cp execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll1 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll1/
[info md5sum.c] 0387eee9820fa224525ff8b2e0dfa9be quick md5sum computed on 24546 bytes
[info md5sum.c] 0387eee9820fa224525ff8b2e0dfa9be  full md5sum computed on 24546 bytes
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : UNUSED -> TOKEEP
[info md5sum.c] 1a167d608e76a6a4a8b16d168580873c quick md5sum computed on 20480 bytes
[info md5sum.c] 1a167d608e76a6a4a8b16d168580873c  full md5sum computed on 20480 bytes
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : UNUSED -> AVAILABLE
[info md5sum.c] 0a7ecd447ef2acb3b5c6e4c550e6636f quick md5sum computed on 374784 bytes
[info md5sum.c] 0a7ecd447ef2acb3b5c6e4c550e6636f  full md5sum computed on 374784 bytes
[info cacheTree.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 (score= 3.75) : UNUSED -> TOKEEP
[info md5sum.c] de5008799752552b7963a2670dc5eb18 quick md5sum computed on 391168 bytes
[info md5sum.c] de5008799752552b7963a2670dc5eb18  full md5sum computed on 391168 bytes
[info cacheTree.c] de5008799752552b7963a2670dc5eb18:391168 (score=10.00) : UNUSED -> USED
[notice utnotify.c] .......................................................
[notice utnotify.c] we have :
[notice utnotify.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll1               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     6b18ed0194b0fbadd08e0a13cccda00e
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] D 2010-01-01,01:00:00 6b18ed0194b0fbadd08e0a13cccda00e 022a34b2f9b893fba5774237e1aa80ea               24075 test@test.com
[notice recordTree.c] # ^ FINAL_DEMAND

[notice recordTree.c] D 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 !wanted
[notice recordTree.c] # ^ REMOTE_DEMAND

[notice recordTree.c] S 2010-01-01,01:00:00 6b18ed0194b0fbadd08e0a13cccda00e 0387eee9820fa224525ff8b2e0dfa9be               24546 logo.tgz
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 6b18ed0194b0fbadd08e0a13cccda00e 0a7ecd447ef2acb3b5c6e4c550e6636f              374784 logoP2.iso
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 6b18ed0194b0fbadd08e0a13cccda00e 1a167d608e76a6a4a8b16d168580873c               20480 logoP1.cat
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:00:00 6b18ed0194b0fbadd08e0a13cccda00e de5008799752552b7963a2670dc5eb18              391168 /HERE/misc/logoP1.iso:supports/
[notice recordTree.c] # ^ FINAL_SUPPLY

[notice utnotify.c] -------------------------------------------------------
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll1 collection (5SX )
[info openClose.c] steps: 0 / 93
[info notify.c] find a remote demand to work on: 022a34b2f9b893fba5774237e1aa80ea:24075
[info notify.c] found an archive to notify: 0387eee9820fa224525ff8b2e0dfa9be:24546
[info notify.c] found a final demand to notify: 022a34b2f9b893fba5774237e1aa80ea:24075
[info notify.c] found a bad score's local top container to notify: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info address.c] build socket address 127.0.0.1:11111
[info connect.c] connected to localhost (746d6ceeb76e05cfa2dea92a1c5753cd)
[info recordTree.c] # Collection's records:
[info recordTree.c] Headers
[info recordTree.c]   Collection coll1               
[info recordTree.c]   Type       NOTIFY
[info recordTree.c]   Server     6b18ed0194b0fbadd08e0a13cccda00e
[info recordTree.c]   DoCypher   FALSE
[info recordTree.c] Body
[info recordTree.c] #                date                             host                             hash                size extra
[info recordTree.c] D 2010-01-01,01:00:00 6b18ed0194b0fbadd08e0a13cccda00e 022a34b2f9b893fba5774237e1aa80ea               24075 !wanted
[info recordTree.c] # ^ LOCAL_DEMAND

[info recordTree.c] S 2010-01-01,01:00:00 6b18ed0194b0fbadd08e0a13cccda00e 0387eee9820fa224525ff8b2e0dfa9be               24546 logo.tgz
[info recordTree.c] # ^ LOCAL_SUPPLY

[info recordTree.c] S 2010-01-01,01:00:00 6b18ed0194b0fbadd08e0a13cccda00e 0a7ecd447ef2acb3b5c6e4c550e6636f              374784 logoP2.iso
[info recordTree.c] # ^ LOCAL_SUPPLY

[notice notify.c] localhost:11111 notified
[err address.c] gethostbyname_r mediatex.org: Unknown host
[err address.c] getIpFromHostname fails
[err address.c] buildSocketAddress fails
[err connect.c] buildServerAddress fails
[err connect.c] connectServer fails
[notice notify.c] cannot connect mediatex.org
[notice utnotify.c] -------------------------------------------------------
[notice utnotify.c] Clean the cache:
[notice utnotify.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : WANTED -> WANTED
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : WANTED -> UNUSED
[info cacheTree.c] 0387eee9820fa224525ff8b2e0dfa9be:24546 (score= 3.75) : TOKEEP -> UNUSED
[info cacheTree.c] 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 (score= 3.75) : TOKEEP -> UNUSED
[info cacheTree.c] 1a167d608e76a6a4a8b16d168580873c:20480 (score=10.00) : AVAILABLE -> UNUSED
[info cacheTree.c] de5008799752552b7963a2670dc5eb18:391168 (score=10.00) : USED -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/tmp/mdtx2-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll2/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/tmp/mdtx2-coll2/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll3/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/tmp/mdtx2-coll3/*
[info command.c] /bin/bash execution returns 0
[notice utnotify.c] -------------------------------------------------------
[notice utnotify.c] *** test receiving message:
[notice utnotify.c] .......................................................
[notice utnotify.c] -------------------------------------------------------
[notice utnotify.c] Build message:
[notice utnotify.c] .......................................................
[notice utnotify.c] -------------------------------------------------------
[notice utnotify.c] message we receive :
[notice utnotify.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll1               
[notice recordTree.c]   Type       NOTIFY
[notice recordTree.c]   Server     6b18ed0194b0fbadd08e0a13cccda00e
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] D 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 !wanted
[notice recordTree.c] # ^ REMOTE_DEMAND

[notice utnotify.c] .......................................................
[notice utnotify.c] actually we have :
[notice utnotify.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll1               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     6b18ed0194b0fbadd08e0a13cccda00e
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice utnotify.c] -------------------------------------------------------
[notice notify.c] forward message to mediatex.org:33333 nat client
[err address.c] gethostbyname_r mediatex.org: Unknown host
[err address.c] getIpFromHostname fails
[err address.c] buildSocketAddress fails
[err connect.c] buildServerAddress fails
[err connect.c] connectServer fails
[notice notify.c] cannot connect mediatex.org
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> WANTED
[notice utnotify.c] .......................................................
[notice utnotify.c] Now we have :
[notice utnotify.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll1               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     6b18ed0194b0fbadd08e0a13cccda00e
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] D 2010-01-01,01:00:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 !wanted
[notice recordTree.c] # ^ REMOTE_DEMAND

[notice utnotify.c] -------------------------------------------------------
[notice utnotify.c] -------------------------------------------------------
[notice utnotify.c] Clean the cache:
[notice utnotify.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : WANTED -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/tmp/mdtx2-coll1/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll2/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/tmp/mdtx2-coll2/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/cache/mdtx2-coll3/*
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx2/tmp/mdtx2-coll3/*
[info command.c] /bin/bash execution returns 0
[info confTree.c] free configuration
[info utnotify.c] exit on success
