[info confFile.y] parse configuration from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1/mdtx1.conf
[notice utupload.c] -------------------------------------------------------
[notice utupload.c] Clean the cache:
[notice utupload.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll1/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll1 collection ( SX )
[info serverFile.y] parse coll1 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll1/servers.txt
[info extractFile.y] parse coll1 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll1/extract000.txt
[info openClose.c] steps: 93 / 93
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll2/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll2 collection ( SX )
[info serverFile.y] parse coll2 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll2/servers.txt
[info extractFile.y] parse coll2 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll2/extract000.txt
[info openClose.c] steps: 93 / 93
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection ( SX )
[info serverFile.y] parse coll3 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll3/servers.txt
[info extractFile.y] parse coll3 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll3/extract000.txt
[info openClose.c] steps: 93 / 93
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] parse records file: LOCALSTATEDIR/cache/mediatex/mdtx1/md5sums/mdtx1-coll3.md5
[notice openClose.c] no md5sums file: LOCALSTATEDIR/cache/mediatex/mdtx1/md5sums/mdtx1-coll3.md5
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[notice utupload.c] .......................................................
[notice utupload.c] Scan gives :
[notice utupload.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice utupload.c] -------------------------------------------------------
[notice utupload.c] -------------------------------------------------------
[notice utupload.c]  * No message ring:
[notice utupload.c] .......................................................
[err upload.c] uploadFinaleArchive fails
[notice utupload.c] reply : 310 empty message
[notice utupload.c] -------------------------------------------------------
[notice utupload.c]  * Empty message ring:
[notice utupload.c] .......................................................
[err upload.c] uploadFinaleArchive fails
[notice utupload.c] reply : 310 empty message
[notice utupload.c] -------------------------------------------------------
[notice utupload.c]  * Not a final suply:
[notice utupload.c] .......................................................
[err upload.c] uploadFinaleArchive fails
[notice utupload.c] reply : 332 message do not provide a final supply notBeginningWithSlash
[notice utupload.c] -------------------------------------------------------
[notice utupload.c]  * Upload using default target:
[notice utupload.c] .......................................................
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cacheTree.c] 3f18841537668dcf4fafd1471c64d52d:1937 (score=-1.00) : UNUSED -> USED
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used              0
[info cache.c] = free      104857600
[info cache.c]   total     104857600
[info cache.c] - frozen            0
[info cache.c] = avail     104857600
[info cache.c] need             1937
[info cacheTree.c] 3f18841537668dcf4fafd1471c64d52d:1937 (score=-1.00) : USED -> ALLOCATED
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/2010-01
[info device.c] not a symlink: /HERE/misc/README
[info device.c] do not match a block device: /HERE/misc/README
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: /HERE/misc/README
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/2010-01/README
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/2010-01
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/2010-01/README to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/2010-01/README
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/2010-01/README
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/2010-01/README
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info cacheTree.c] 3f18841537668dcf4fafd1471c64d52d:1937 (score=-1.00) : ALLOCATED -> TOKEEP
[notice extract.c] 3f18841537668dcf4fafd1471c64d52d:1937 extracted
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/2010-01
[notice extract.c] 3f18841537668dcf4fafd1471c64d52d:1937 found
[info cacheTree.c] 3f18841537668dcf4fafd1471c64d52d:1937 (score=-1.00) : TOKEEP -> TOKEEP
[notice utupload.c] .......................................................
[notice utupload.c] We get 210 ok
[notice utupload.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd 3f18841537668dcf4fafd1471c64d52d                1937 2010-01/README
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice utupload.c] -------------------------------------------------------
[notice utupload.c] -------------------------------------------------------
[notice utupload.c]  * Already there:
[notice utupload.c] .......................................................
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[err upload.c] uploadFinaleArchive fails
[notice utupload.c] reply : 313 already exists 3f18841537668dcf4fafd1471c64d52d:1937
[notice utupload.c] -------------------------------------------------------
[notice utupload.c] Clean the cache:
[notice utupload.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll1/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll2/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info cacheTree.c] 3f18841537668dcf4fafd1471c64d52d:1937 (score=-1.00) : TOKEEP -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cache.c] scaning directory: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/
[notice utupload.c] -------------------------------------------------------
[notice utupload.c]  * Upload providing a target: store
[notice utupload.c] .......................................................
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cacheTree.c] 3f18841537668dcf4fafd1471c64d52d:1937 (score=-1.00) : UNUSED -> USED
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used              0
[info cache.c] = free      104857600
[info cache.c]   total     104857600
[info cache.c] - frozen            0
[info cache.c] = avail     104857600
[info cache.c] need             1937
[info cacheTree.c] 3f18841537668dcf4fafd1471c64d52d:1937 (score=-1.00) : USED -> ALLOCATED
[info device.c] not a symlink: /HERE/misc/README
[info device.c] do not match a block device: /HERE/misc/README
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: /HERE/misc/README
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/store
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/store to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/store
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/store
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/store
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info cacheTree.c] 3f18841537668dcf4fafd1471c64d52d:1937 (score=-1.00) : ALLOCATED -> TOKEEP
[notice extract.c] 3f18841537668dcf4fafd1471c64d52d:1937 extracted
[notice extract.c] 3f18841537668dcf4fafd1471c64d52d:1937 found
[info cacheTree.c] 3f18841537668dcf4fafd1471c64d52d:1937 (score=-1.00) : TOKEEP -> TOKEEP
[notice utupload.c] .......................................................
[notice utupload.c] We get 210 ok
[notice utupload.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd 3f18841537668dcf4fafd1471c64d52d                1937 store
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice utupload.c] -------------------------------------------------------
[notice utupload.c] -------------------------------------------------------
[notice utupload.c]  * Upload providing a target: store/it/here
[notice utupload.c] .......................................................
[info openClose.c] estimate 93 steps for load
[info openClose.c] parse coll3 collection (5 X )
[info openClose.c] steps: 0 / 93
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : UNUSED -> USED
[info cache.c] cache sizes:
[info cache.c]   total     104857600
[info cache.c] - used           1937
[info cache.c] = free      104855663
[info cache.c]   total     104857600
[info cache.c] - frozen         1937
[info cache.c] = avail     104855663
[info cache.c] need            24075
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : USED -> ALLOCATED
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/store
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/store/it
[info device.c] not a symlink: /HERE/misc/logo.png
[info device.c] do not match a block device: /HERE/misc/logo.png
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: /HERE/misc/logo.png
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/store/it/here
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/store_00
[info perm.c] mkdir LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/store_00/it
[info extract.c] move LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/store/it/here to LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/store_00/it/here
[notice extract.c] do cp
[info command.c] execScript: /bin/cp
[info command.c]  arg1: -f
[info command.c]  arg2: LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/store/it/here
[info command.c]  arg3: LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/store_00/it/here
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/cp execution returns 0
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : ALLOCATED -> TOKEEP
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 extracted
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/store/it
[info perm.c] rmdir LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/store
[notice extract.c] 022a34b2f9b893fba5774237e1aa80ea:24075 found
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> TOKEEP
[notice utupload.c] .......................................................
[notice utupload.c] We get 210 ok
[notice utupload.c] .......................................................
[notice recordTree.c] # Collection's records:
[notice recordTree.c] Headers
[notice recordTree.c]   Collection coll3               
[notice recordTree.c]   Type       UNKNOWN
[notice recordTree.c]   Server     746d6ceeb76e05cfa2dea92a1c5753cd
[notice recordTree.c]   DoCypher   FALSE
[notice recordTree.c] Body
[notice recordTree.c] #                date                             host                             hash                size extra
[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd 022a34b2f9b893fba5774237e1aa80ea               24075 store_00/it/here
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice recordTree.c] S 2010-01-01,01:05:00 746d6ceeb76e05cfa2dea92a1c5753cd 3f18841537668dcf4fafd1471c64d52d                1937 store
[notice recordTree.c] # ^ LOCAL_SUPPLY

[notice utupload.c] -------------------------------------------------------
[notice utupload.c] -------------------------------------------------------
[notice utupload.c] Clean the cache:
[notice utupload.c] .......................................................
[notice utFunc.c] clean the cache
[notice utFunc.c] clean cache for all collections
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll1/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll2/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll2/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info cacheTree.c] 022a34b2f9b893fba5774237e1aa80ea:24075 (score= 8.25) : TOKEEP -> UNUSED
[info cacheTree.c] 3f18841537668dcf4fafd1471c64d52d:1937 (score=-1.00) : TOKEEP -> UNUSED
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll3/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info command.c] execScript: /bin/bash
[info command.c]  arg1: -c
[info command.c]  arg2: rm -fr LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll3/*
[info command.c] --- exec system call begin ---
[info command.c] hide stdout from child (use '-sdebug:script' to show)
[info command.c] --- exec system call end ---
[info command.c] /bin/bash execution returns 0
[info confTree.c] free configuration
[info utupload.c] exit on success
