[debug utinclude.sh] test for include.sh

* Autotools inputs:
MEDIATEX=/mediatex
BINDIR=BINDIR
DATAROOTDIR=DATAROOTDIR
EXEC_PREFIX=EXEC_PREFIX
LOCALSTATEDIR=LOCALSTATEDIR
PREFIX=EXEC_PREFIX
SYSCONFDIR=SYSCONFDIR

* absolute paths:
ETCDIR=SYSCONFDIR/mediatex
DATADIR=DATAROOTDIR/mediatex
STATEDIR=LOCALSTATEDIR/lib/mediatex
CACHEDIR=LOCALSTATEDIR/cache/mediatex
PIDDIR=LOCALSTATEDIR/run/mediatex
SCRIPTS=DATAROOTDIR/mediatex/scripts
MISC=DATAROOTDIR/mediatex/misc
HOSTSSH=SYSCONFDIR/ssh

* recurent variables:
GITBARE=LOCALSTATEDIR/lib/mediatex/mdtx
MDTXHOME=LOCALSTATEDIR/cache/mediatex/mdtx
MD5SUMS=LOCALSTATEDIR/cache/mediatex/mdtx/md5sums
CACHES=LOCALSTATEDIR/cache/mediatex/mdtx/cache
EXTRACTLOCALSTATEDIR/cache/mediatex/mdtx/tmp
GITCLT=LOCALSTATEDIR/cache/mediatex/mdtx/git
JAIL=LOCALSTATEDIR/cache/mediatex/mdtx/jail
HOMES=LOCALSTATEDIR/cache/mediatex/mdtx/home
MDTXGIT=LOCALSTATEDIR/cache/mediatex/mdtx/git/mdtx
CONFFILE=LOCALSTATEDIR/cache/mediatex/mdtx/git/mdtx/mdtx.conf
PIDFILE=LOCALSTATEDIR/run/mediatex/mdtxd.pid

* Command line inputs:
LOG_FILE=
LOG_FACILITY=file
LOG_SEVERITY=debug
DRY_RUN=0
MDTX=mdtx
[info utinclude.sh] success
