@cindex server

The @activity{Server} manage local cache integrity and 
exchange files with other @sc{Mediatex}'s @activity{Server}s.
@activityClient{} may ask it to updates the 
@dataChecksum{} file
that gives the local cache's status.

The @activity{server} activity is diveded into 6 process:
@menu
* cache::       @process{cache}
* extract::     @process{extract}
* cgiServer::   @process{cgiServer}
* have::        @process{have}
* srvUpload::   @process{upload}
* notify::      @process{notify}
* delivering::  @process{delivering}
@end menu

Flood diagram:

@image{mediatex-figures/server,,,,}

@itemize @bullet
@item Events in
@table @code

@item @eventServerStart 
@itemx @eventServerStop
@itemx @eventServerReload
from @procScriptsInitd{}: standard @acronym{UNIX} process management (HUP signal for reload...).

@item @eventServerSaveReg
from @procClientMisc{}: serialize the last cache status into a file.

@item @eventServerExtractReg
@itemx @eventServerNotifyReg 
@itemx @eventServerDeliverReg
from @activityClientO respectively to 
@procServerExtract{}, @procServerNotify{} and @procServerDeliver{}: ask to extract, notify or deliver (no more used) by setting a value into share memory and sending a signal.

@item @eventServerCgiQuery 
from @procScriptsCgi to @procServerCgiSrv{}: receive a socket query asking for an archive.

@item @eventServerHaveQuery 
from @procClientSupp to @procServerHave{}: receive a socket query providing archives from a support.

@item @eventServerUploadQuery
from @procClientMisc to @procServerCache{}: receive a socket query providing an archive and asking to handle it into the cache.

@item @eventServerNotifyQuery
from a remote @activityServerO to @procServerNotify{}: receive a socket query providing remote cache content index.

@end table
@item Processing

Manage HUP signal to re-scan the cache 
and serialising the last cache status in order to keep in mind remote supplies and demands on next start-up.

@item Events out
@table @code

@item @eventClientMiscBind
@itemx @eventClientMiscUnBind
@itemx @eventClientMiscGet
to @procClientMisc{}: tel client to make operation that needs privileges, like binding directories into the chroot jail and using collection account to retrieve archives remotely.

@item @eventClientSuppMount
@itemx @eventClientSuppUMount
from @procServerExtract to @procClientSupp{}: tel client to mount supports as it need root privileges.

@item @eventServerNotifyQuery
from @procServerNotify{} to a remote @activityServerO{}: send a socket query providing local cache content index.

@item @eventScriptsDeliver 
@item @eventScriptsAudit
from @procServerDeliver to @procScriptsDeliver or @procScriptsAudit{}: respectively notify archive availability to @actorUserO{} or audit an archive.

@end table

@item Data in
@table @code
@c @item @dataConf
@item @dataConfO{} (@pxref{mdtx.conf})
@item @dataServersO{} (@pxref{servers.txt})
@end table

@item Data in/out
@table @code
@c @item @dataChecksum
@item @dataChecksumO (@pxref{mdtxCOLL.md5})
@end table
@end itemize

Code:
@table @file
@item /etc/init.d/mediatex/mdtxd
@itemx src/server/threads.c
@itemx src/mdtxd.c
@end table

@node cache
@subsection cache
@include cache.texi
@node extract
@subsection extract
@include extract.texi
@node cgiServer
@subsection cgiServer
@include cgiServer.texi
@node have
@subsection have
@include have.texi
@node srvUpload
@subsection srvUpload
@include srvUpload.texi
@node notify
@subsection notify
@include notify.texi
@node delivering
@subsection delivering
@include delivering.texi
