@cindex server

The @activity{Server} manage local cache integrity and 
exchange files with other @sc{Mediatex}'s @activity{Server}s.
@activityClient{} may ask it to updates the 
@dataChecksum{} file
that gives the local cache's status.

The @activity{server} activity is diveded into 6 process:
@menu
* cache::       @process{cache}
* extract::     @process{extract}
* cgiServer::   @process{cgiServer}
* have::        @process{have}
* srvUpload::   @process{upload}
* notify::      @process{notify}
* delivering::  @process{delivering}
@end menu

Flood diagram:

@image{mediatex-figures/server,,,,}

@itemize @bullet
@item Events in
@table @code
@item @eventServerStart 
@itemx @eventServerStop
@item @eventServerReload
from @procScriptsInitd
@item @eventServerSaveReg
from @procClientMisc
@item @eventServerExtractReg
@itemx @eventServerNotifyReg 
@itemx @eventServerDeliverReg
from @procClientMisc{} respectively to 
@procServerExtract{}, @procServerNotify{} and @procServerDeliver
@item @eventServerCgiQuery 
from @procScriptsCgi{} to @procServerCgiSrv
@item @eventServerHaveQuery 
from @procClientSupp{} to @procServerHave
@item @eventServerUpload
from @procClientMisc{} to @procServerCache
@end table

@item Events out
@table @code
@item @eventClientMiscBind
@itemx @eventClientMiscUnBind
@itemx @eventClientMiscGet
to @procClientMisc
@item @eventClientSuppMount
@itemx @eventClientSuppUMount
from @procServerExtract{} to @procClientSupp
@item @eventScriptsDeliver 
from @procServerDeliver{} to @procScriptsDeliver
@end table

@item Data in
@table @code
@c @item @dataConf
@item @dataConfO{} (@pxref{mdtx.conf})
@item @dataServersO{} (@pxref{servers.txt})
@end table

@item Data in/out
@table @code
@c @item @dataChecksum
@item @dataChecksumO (@pxref{mdtxCOLL.md5})
@end table
@end itemize

Code:
@table @file
@item /etc/init.d/mediatex/mdtxd
@itemx src/server/threads.c
@itemx src/server/mdtx.c
@end table

@node cache
@subsection cache
@include cache.texi
@node extract
@subsection extract
@include extract.texi
@node cgiServer
@subsection cgiServer
@include cgiServer.texi
@node have
@subsection have
@include have.texi
@node srvUpload
@subsection srvUpload
@include srvUpload.texi
@node notify
@subsection notify
@include notify.texi
@node delivering
@subsection delivering
@include delivering.texi
