@cindex specifications

The information system is divided into 4 activities:
@menu
* Tools::       @activity{Tools}
* Scripts::     @activity{Scripts}
* Client::      @activity{Client}
* Server::      @activity{Server}
@end menu

Flood diagram:

@image{mediatex-figures/specs,,,,}
@itemize @bullet

@item Events in
@table @code

@item @eventScriptsInitdStart{} 
@itemx @eventScriptsInitdStop
@itemx @eventScriptsInitdStatus
@itemx @eventScriptsInitdReload
from @actorAdmin{} to @procScriptsInitd{}: start/stop the @mediatexO{} daemon.

@item @eventClientMiscInit
@itemx @eventClientMiscRemove
@itemx @eventClientMiscPurge
@itemx @eventClientMiscAddUser
@itemx @eventClientMiscDelUser
from @actorAdminO{} to @procClientMisc{}: configure the @mediatexO{} system.

@item @eventClientConfAddColl
@itemx @eventClientConfDelColl
from @actorAdminO{} to @procClientConf{}: configure collections.

@item @eventToolsCronDate
from @actorDate{} to @procToolsCron{}: scheduled tasks.

@item @eventClientServAddKey
@itemx @eventClientServDelKey
@itemx @eventClientServUpgrade
from @actorPublisher{} to @procClientServ{}: manage collection settings.

@item @eventClientConfList
@itemx @eventClientConfShareSupport
@itemx @eventClientConfWithdrawSupp
from @actorPublisherO{} to @procClientConf{}: list collections ; share/withdraw local supports to collections.

@item @eventClientSuppList
@itemx @eventClientSuppAdd
@itemx @eventClientSuppFileAdd
@itemx @eventClientSuppDel
@itemx @eventClientSuppNote
@itemx @eventClientSuppCheck
from @actorPublisherO{} to @procClientSupp{}: manage local supports.

@item @eventClientUpload
from @actorPublisherO{} to @procClientUpload{}: upload an incoming archive into the cache.

@item @eventClientMiscMake{} 
@itemx @eventClientMiscClean
@itemx @eventClientMiscSu
@itemx @eventClientMiscAudit
from @actorPublisherO{} to @procClientMisc{}: build/clean the @acronym{HTML} catalogue ; change to server or collection system user ; simulate retrieving all archives.

@item @eventToolsApacheHttpGet{} 
@itemx @eventToolsApacheHttpPost{} 
@itemx @eventToolsApacheStartDownload
from @actorUser{} to @procToolsApache{}: @actorUserO{}'s queries generated by its internet browser.

@end table
@item Processing

@pxref{What}

@item Events out
@table @code

@item @eventActorPublisherMotd
from @procToolsCron{} to @actorPublisherO{}: message of the day the @actorPublisherO{} see at log-in.

@item @eventActorUserHtmlForm{} 
(if archive is not available) ...
@item @eventActorUserHtmlRedirect{} 
(if archive is available) @*
from @procToolsApache{} to @actorUserO{}: replies to the @actorUserO{}'s internet browser.

@item @eventActorUserMail{} 
from @procToolsExim{} to @actorUserO{}: archive availability notification.

@item @eventActorPublisherMail{} 
from @procToolsExim{} to @actorPublisherO{}: audit availability notification.

@item @eventActorAdminMail
from @procToolsExim{} to @actorAdminO{}: scheduled task error notification.

@end table
@item Data in/out
@itemize @bullet
@item @dataConf
@item @dataSupp
@item @dataServers
@item @dataCatalog
@item @dataExtract
@item @dataChecksum
@end itemize
@end itemize

@c Code:

@node Tools
@section Tools
@include tools.texi
@node Scripts
@section Scripts
@include scripts.texi
@node Client
@section Client
@include client.texi
@node Server
@section Server
@include server.texi
