@cindex specifications

The information system is diveded into 4 activities:
@menu
* Tools::       @activity{Tools}
* Scripts::     @activity{Scripts}
* Client::      @activity{Client}
* Server::      @activity{Server}
@end menu

Flood diagram:

@image{mediatex-figures/specs,,,,}
@itemize @bullet

@item Events in
@table @code
@item @eventScriptsInitdStart 
@itemx @eventScriptsInitdStop
@itemx @eventScriptsInitdStatus
@itemx @eventScriptsInitdReload
from 
@actorAdmin{} to @procScriptsInitd{}: start/stop the @mediatexO{} daemon.
@item @eventClientMiscInit
@itemx @eventClientMiscRemove
@itemx @eventClientMiscPurge
@itemx @eventClientMiscAddUser
@itemx @eventClientMiscDelUser
from @actorAdminO{} to @procClientMisc{}: configure the @mediatexO{} system.
@item @eventClientConfAddColl
@itemx @eventClientConfDelColl
from @actorAdminO{} to @procClientConf{}: create/destroy or (un)subscribe to a new collection. 
@item @eventToolsCronDate
from 
@actorDate{} 
to @procToolsCron
@item @eventClientServAddKey
@itemx @eventClientServDelKey
@itemx @eventClientServUpgrade
from 
@actorPublisher{} 
to @procClientServ{}: accept/revoke a remote server ; upgrade local configuration.
@item @eventClientConfList
@itemx @eventClientConfShareSupport
@itemx @eventClientConfWithdrawSupp
from @actorPublisherO{} to @procClientConf{}: list collections ; share/withdraw local supports to collections; connect with @acronym{nat} servers.
@item @eventClientSuppList
@itemx @eventClientSuppAdd
@itemx @eventClientSuppFileAdd
@itemx @eventClientSuppDel
@itemx @eventClientSuppNote
@itemx @eventClientSuppCheck
from @actorPublisherO{} to @procClientSupp{}: add/del/provide local supports.
@item @eventClientUpload
from @actorPublisherO{} to @procClientUpload{}: upload a new fileinto the cache.
@item @eventClientMiscMake 
@itemx @eventClientMiscClean
@itemx @eventClientMiscSu
@itemx @eventClientMiscAudit
from @actorPublisherO{} to @procClientMisc{}: build/clean the @acronym{HTML} catalog ; change to server or collection user ; simulate retrieving all archives.
@item @eventToolsApacheHttpGet 
@itemx @eventToolsApacheHttpPost 
@itemx @eventToolsApacheStartDownload
from 
@actorUser{} 
to @procToolsApache{}: generated by browser.
@end table

@item Events out
@table @code
@item @eventActorPublisherMotd
from @procToolsCron{} to @actorPublisherO
@item @eventActorUserHtmlForm 
@itemx @eventActorUserHtmlRedirect 
from @procToolsApache{} to @actorUserO{} depending if archive is available or not.
@item @eventActorUserMail 
from @procToolsExim{} to @actorUserO
@item @eventActorPublisherMail 
from @procToolsExim{} to @actorPublisherO
@item @eventActorAdminMail
from @procToolsCron{} to @actorAdminO
@end table

@item Data in/out
@itemize @bullet
@item @dataConf
@item @dataSupp
@item @dataServers
@item @dataCatalog
@item @dataExtract
@item @dataChecksum
@end itemize
@end itemize

@c Code:

@node Tools
@section Tools
@include tools.texi
@node Scripts
@section Scripts
@include scripts.texi
@node Client
@section Client
@include client.texi
@node Server
@section Server
@include server.texi
