[info cvsPrint.c] serialize into filename000.txt
the lines should not be cut
put 2nd line in same file

# Local Variables:
# mode: conf
# mode: font-lock
# End:
[info cvsPrint.c] serialize into filename001.txt
3rd line ...

# Local Variables:
# mode: conf
# mode: font-lock
# End:
[info cvsPrint.c] serialize into filename002.txt
4rth line ...

# Local Variables:
# mode: conf
# mode: font-lock
# End:
[info utcvsPrint.c] exit on success
