[info cvsPrint.c] serialize into filename00.txt
the lines should not be cut
put 2nd line in same file

# Local Variables:
# mode: conf
# mode: font-lock
# End:
[info cvsPrint.c] serialize into filename01.txt
3rd line ...

# Local Variables:
# mode: conf
# mode: font-lock
# End:
[info cvsPrint.c] serialize into filename02.txt
4rth line ...

# Local Variables:
# mode: conf
# mode: font-lock
# End:
[info cvsPrint.c] exit on success
