[debug log.c] logging to the standard error
[debug log.c] started
[debug command.c] set the environment variables
[debug openClose.c] get coll1 collection
[debug openClose.c] load configuration
[debug locks.c] lock file for read
[debug locks.c] unlock file
[debug perm.c] checkDirectory LOCALSTATEDIR/cache/mediatex/mdtx1/home/mdtx1-coll1 mdtx1-coll1 mdtx1 750
[debug perm.c] checkDirectory LOCALSTATEDIR/cache/mediatex/mdtx1/cache/mdtx1-coll1 mdtx1 mdtx1-coll1 2750
[debug perm.c] checkDirectory LOCALSTATEDIR/cache/mediatex/mdtx1/tmp/mdtx1-coll1 mdtx1 mdtx1-coll1 2770
[debug perm.c] checkDirectory LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll1 mdtx1 mdtx1-coll1 2770
[debug perm.c] checkDirectory LOCALSTATEDIR/cache/mediatex/mdtx1/home/mdtx1-coll1/.ssh mdtx1-coll1 mdtx1-coll1 700
[debug perm.c] checkDirectory LOCALSTATEDIR/cache/mediatex/mdtx1/home/mdtx1-coll1/public_html mdtx1 mdtx1-coll1 2750
[debug extractScore.c] computeExtractScore: coll1
[debug openClose.c] load coll1 collection ( SX )
[debug openClose.c] loadCollectionNbSteps
[info openClose.c] estimate 87 steps for load
[info openClose.c] parse coll1 collection ( SX )
[debug openClose.c] file loop on coll1 collection ( SX )
[debug openClose.c] do load coll1 collection (  X )
[debug openClose.c] load   X  files
[debug locks.c] lock file for read
[debug extractFile.y] extr_set_debug = 0
[debug locks.c] unlock file
[debug openClose.c] do load coll1 collection ( S  )
[debug locks.c] lock file for read
[debug serverFile.y] serv_set_debug = 0
[debug locks.c] unlock file
[info openClose.c] steps: 87 / 87
[debug extractScore.c] populateExtractTree: coll1
[debug extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[debug extractScore.c]    7.50
[debug extractScore.c]   14.00
[debug extractScore.c] = 21.50
[debug extractScore.c] / 2
[debug extractScore.c] > 10.00
[debug extractScore.c] -------
[debug extractScore.c] = 10.00
[debug extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[debug extractScore.c]   10.00
[debug extractScore.c]    2.00
[debug extractScore.c] + 12.00
[debug extractScore.c] = 24.00
[debug extractScore.c] / 2
[debug extractScore.c] > 10.00
[debug extractScore.c] -------
[debug extractScore.c] = 10.00
[debug extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[debug extractScore.c]   17.50
[debug extractScore.c] = 17.50
[debug extractScore.c] / 2
[debug extractScore.c] -------
[debug extractScore.c] =  8.75
[debug extractScore.c]  computeArchive: 022a34b2f9b893fba5774237e1aa80ea:24075
[debug extractScore.c]   computeContainer TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546
[debug extractScore.c]    computeArchive: 0387eee9820fa224525ff8b2e0dfa9be:24546
[debug extractScore.c]     computeContainer CAT/1a167d608e76a6a4a8b16d168580873c:20480
[debug extractScore.c]      computeArchive: 1a167d608e76a6a4a8b16d168580873c:20480
[debug extractScore.c]       computeContainer ISO/de5008799752552b7963a2670dc5eb18:391168
[debug extractScore.c]        computeArchive: de5008799752552b7963a2670dc5eb18:391168
[debug extractScore.c]         archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[debug extractScore.c]        container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[debug extractScore.c]       archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[debug extractScore.c]      computeArchive: c0c055a0829982bd646e2fafff01aaa6:4066
[debug extractScore.c]       computeContainer ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[debug extractScore.c]        computeArchive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[debug extractScore.c]         archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 8.75
[debug extractScore.c]        container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 8.75
[debug extractScore.c]       archive c0c055a0829982bd646e2fafff01aaa6:4066 = 8.75
[debug extractScore.c]      container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 8.75
[debug extractScore.c]     archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 8.75
[debug extractScore.c]    container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 8.75
[debug extractScore.c]   computeContainer TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045
[debug extractScore.c]    computeArchive: b5810aba99ed0d15f1f0a073e646d5bd:25045
[debug extractScore.c]     archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[debug extractScore.c]    container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[debug extractScore.c]   computeContainer AFIO/65f1464142f405dbbeeea4830c95ddd3:25600
[debug extractScore.c]    computeArchive: 65f1464142f405dbbeeea4830c95ddd3:25600
[debug extractScore.c]     archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[debug extractScore.c]    container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[debug extractScore.c]   computeContainer TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720
[debug extractScore.c]    computeArchive: f54fba7d2e070d48051ac3f8f1c2eb98:30720
[debug extractScore.c]     archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[debug extractScore.c]    container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[debug extractScore.c]   computeContainer CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088
[debug extractScore.c]    computeArchive: b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088
[debug extractScore.c]     computeContainer GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457
[debug extractScore.c]      computeArchive: 3a04277dd1f43740a5fe17fd0ae9a5aa:24457
[debug extractScore.c]       archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[debug extractScore.c]      container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[debug extractScore.c]     computeContainer BZIP/fa2b0b536bf61f61617528c474e0bf61:24973
[debug extractScore.c]      computeArchive: fa2b0b536bf61f61617528c474e0bf61:24973
[debug extractScore.c]       archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[debug extractScore.c]      container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[debug extractScore.c]     archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[debug extractScore.c]    container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[debug extractScore.c]   computeContainer ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733
[debug extractScore.c]    computeArchive: d79581b67ec1932fd276dcf3b6d6db9a:24733
[debug extractScore.c]     archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[debug extractScore.c]    container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[debug extractScore.c]   computeContainer RAR/7808473c7db9a9e3493a6b61f44f8805:20480
[debug extractScore.c]    computeArchive: 7808473c7db9a9e3493a6b61f44f8805:20480
[debug extractScore.c]     archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[debug extractScore.c]    computeArchive: db8b80896f7202b656913f99d438075c:4090
[debug extractScore.c]     archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[debug extractScore.c]    container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[debug extractScore.c]   archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 10.00
[debug extractScore.c]   archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 8.75
[debug extractScore.c]   archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 8.75
[debug extractScore.c]   archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[debug extractScore.c]   archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[debug extractScore.c]   archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[debug extractScore.c]   archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[debug extractScore.c]  computeArchive: b281449c229bcc4a3556cdcc0d3ebcec:815
[debug extractScore.c]    container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 8.75
[debug extractScore.c]    container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[debug extractScore.c]    container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[debug extractScore.c]    container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[debug extractScore.c]    container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[debug extractScore.c]    container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[debug extractScore.c]    container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[debug extractScore.c]   archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 8.75
[debug extractScore.c]   archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[debug extractScore.c]   archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[debug extractScore.c]   archive c0c055a0829982bd646e2fafff01aaa6:4066 = 8.75
[debug extractScore.c]   archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[debug extractScore.c]   archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[debug extractScore.c]   archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[debug extractScore.c]   archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[debug extractScore.c]   archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[debug openClose.c] release coll1 collection ( SX )
[debug openClose.c] file loop on coll1 collection ( SX )
[debug openClose.c] do release coll1 collection (  X )
[debug openClose.c] do release coll1 collection ( S  )
[debug extractScore.c] getExtractStatus: coll1
[debug extractScore.c] extraction score = 8.75
[notice extractScore.c] coll1 collection: Very good perenniality (8.75)
[info utextractScore.c] exit on success
