[info ssh.c] Serializing the authorized_keys file: LOCALSTATEDIR/cache/mediatex/mdtx1/home/mdtx1-coll1/.ssh/authorized_keys
[info ssh.c] Serializing the ssh's config file: LOCALSTATEDIR/cache/mediatex/mdtx1/home/mdtx1-coll1/.ssh/config
[info ssh.c] Serializing the known_host file: LOCALSTATEDIR/cache/mediatex/mdtx1/home/mdtx1-coll1/.ssh/known_hosts
[warning ssh.c] Please avoid having localhost in the servers list
[info utssh.c] exit on success
