[info confFile.y] parse configuration from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1/mdtx1.conf
[info supportFile.y] parse supports from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1/supports.txt
[info serverFile.y] parse coll1 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll1/servers.txt
[info confTree.c] configuration already populated
[info supportFile.y] parse supports from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1/supports.txt
[info upgrade.c] compute support score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 (/HERE/misc/logoP2.iso)
[info upgrade.c] file: = 10.00
[info upgrade.c] compute support score for 022a34b2f9b893fba5774237e1aa80ea:24075 (SUPP11_logo.png)
[warning upgrade.c] "SUPP11_logo.png" support have expired since 12784 days
[info upgrade.c] compute support score for de5008799752552b7963a2670dc5eb18:391168 (SUPP21_logo.part1)
[info upgrade.c] laps > suppTTL: (1 / (1 + 2.00 * (1.00)) ) * 1.00 = 0.33
[info upgrade.c] compute image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info upgrade.c]    0.00
[info upgrade.c] -------
[info upgrade.c] =  0.00
[info upgrade.c] compute image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info upgrade.c]   10.00
[info upgrade.c] -------
[info upgrade.c] = 10.00
[info upgrade.c] compute image score for de5008799752552b7963a2670dc5eb18:391168
[info upgrade.c]    0.33
[info upgrade.c] -------
[info upgrade.c] =  0.33
[info openClose.c] callUpgrade mdtx1-coll1: 746d6ceeb76e05cfa2dea92a1c5753cd ssh://mdtx1-coll1@localhost:/var/lib/gitbare/mdtx1-coll1
[info confTree.c] free configuration
[info utupgrade.c] exit on success

Server 746d6ceeb76e05cfa2dea92a1c5753cd
	comment    "host1.mediatex.org configuration file"
	label      mdtx1
	host       localhost
	lastCommit 2010-01-01,01:00:00 
	mdtxPort   6560
	sshPort    22
	wwwPort    443
	networks   www
	cacheSize  100 Mo
	cacheTTL   15 Day
	queryTTL   1 Week
	provide	  022a34b2f9b893fba5774237e1aa80ea:24075=0.00,
		  0a7ecd447ef2acb3b5c6e4c550e6636f:374784=10.00,
		  de5008799752552b7963a2670dc5eb18:391168=0.33
#	keys:
	userKey    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDlnF3vIn3ad3kMTMdqLa/Q7WK0F2Lm1LbUPTh58ZYcCevtB0Eh4nyEuglApyu0d44/PfcUBAUEBVn3TOwPH6PIU0s7UmiiZpNHSO1cRWuULts8ebE2ePPbKiNj8rcqmTTuoxXB3nnbWtbqJAu4ld6s1P5Rtm84B53dltlkZijCbtBa3FFPpShiRJQ8mIdQBKn5GXg5FDZ6xj9DUVcWAYxmkZXH3Wa2Uy1fSGMhhvSkvzDWJI/m3bBcQQZVJzrrr3Z+KG4MxO2qe1IhOa5Vjlf20PdRy0oB25NU09OfeV+LhfEdDadWvf2lRvcR60RhAf9C4GJOtRSjpO2xo8FNBnjB"
	hostKey    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzupGWlTD1QFcjkNoqyWuAMBo386WHH+B/EVs1pNYBd8NrHvTvFeuvDxOBwIYkI4T7ak0wXLtbW9o0KV2EPtrlGwMelVbM+X4nxXrXtDk5B6Zl0tcPu1NLwHRwhzh8reNXuEqLHE5EfPM1Z8B1eYNoiMEXdCXKzb8dlDXgIe/cjkrS5vJSKicMxb62W2cK9e5I62x+paAQDaDAznvqNFMBXZy/S8t9sqh0CL5ww4+pDXhA9PCdob7EOSA9e4EzgXTMiyyU8Z7gqSqq9DwH4fxiENJLzGbD2e+VM9iPQqp0gI9/4Xn1ZX1x12ddFenAYkLjIZCf8BBAJZRq5WeTwr1B"
end
