[notice utconf.c] *** List collections: 
[info confFile.y] parse configuration from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1/mdtx1.conf
coll1 coll2 coll3
[notice utconf.c] *** List master collections: 
coll1
[notice utconf.c] *** Add a collection:
[info serverFile.y] parse coll4 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll4/servers.txt
[notice utconf.c] *** List collections:
coll1 coll2 coll3 coll4
[notice utconf.c] *** Del collection coll 4:
[info confTree.c] coll4 collection already populated
[info serverTree.c] Serializing the server tree file: stdout
# This file is managed by MediaTeX software.
# MediaTeX mdtx2-coll4@127.0.0.1:22 servers list:

master     6b18ed0194b0fbadd08e0a13cccda00e
collKey    1234567890abcdef
https      yes

# self-ingestion parameters
logApache  no
logGit     no
logAudit   no

# score parameters
uploadTTL  1 Month
serverTTL  2 Week
suppTTL    5 Year
maxScore   10.00
badScore   1.00
powSupp    2.00
factSupp   2.00
fileScore  10.00
minGeoDup  2

Server 6b18ed0194b0fbadd08e0a13cccda00e
	comment    "this is server2"
	label      mdtx2
	host       127.0.0.1
	lastCommit 2010-01-01,01:00:00 
	mdtxPort   6560
	sshPort    22
	wwwPort    80
	networks   private, www
	gateways   private
	cacheSize  200 Mo
	cacheTTL   1 Month
	queryTTL   2 Week
	provide	  022a34b2f9b893fba5774237e1aa80ea:24075=7.50,
		  de5008799752552b7963a2670dc5eb18:391168=10.00
#	keys:
	userKey    "ssh-dss AAAAB3NzaC1kc3MAAACBANTUb46yvsV3bL8AX7oSg48oyN2MPqVCLWL8GiGADVzX71dZmYiqFeTJ5v3vBgk/7rEiaUzfAIZ0ebXhKB1TSc17Vqbdx2DfHm3/IbgBgrBe47VAkbPX+iW2n1zC9fBY5bc/819V0Szf7qvUyzZUkJ/9Vsi79Ikbq7rWu8r3VBeVAAAAFQDTyYPXMe1NzSrUHagG4BLlEQEx7QAAAIEAmYWtuhy0uuoLsoZu96ECnD6Se+buik4WhEi6xuAMPe+/RR7z3IHTh7Xvg56PyfqlFNReFnlc1s23ZZMmWsSAtNYFWqGrir/rddfisDm9Esk5aqPuwi8ToEFikGpthbJZYHjz4PpB2jfWDyLax2HpzFx4vmd1LcrCCM5PtuJ1sEAAAACBALPb55K2CZT3etbLgJ0rfoYDMnutNl38kK5rxf5Ps7Qfq2Uayv1BSKh8arOoMi94qoGKmBDLmwy99raNL4UhVly6YcnOPZ1yhVMfSGy2B1bFHIxh4qhxulm6VsVcPxIQpfwjQCRPImo57jkIjVk49o+K6DY7pDuy60MOmkXPr/sC mdtx@host"
	hostKey    "ssh-dss AAAAB3NzaC1kc3MAAACBANS+fcEeUJYXUH+58diSH8FsHQlj/3xjSVmEf5Od2ip87ro6ZSn3nJI1RR+ALqcLGn/K9fccl4Bj4Oq+M/6iMIL7ZQ6cAwzox9E0w0AjwQg+17WjWIfQNhycnuCCLcg6ThVobZ30RrNFcmwcXKKXP2CRS+eT6Ex8wC42uOEfMvQfAAAAFQDJYtWp9ZaxF1Ej/H0uu8Sqx+9dkQAAAIEAtrLXsPDqCvRwnGtusl1rlzjJCHYMJFZ5eAFDRCdNNUpGqHaHZpw9v8OIt6Qtvx6eVn97opVJ71FG9Xxpl17sIegh8/gprZZlK8ct9Lfs2YFOxcXv+i2r1dVHZwUkwSiYUE59Af71d+Os9VNStTj/U/GXtVNMS7NyqKoaWfFlItgAAACAevPvahBRDZbsjcfhf736q5vyEZbHau5s3VfSQci1u0rIekDhymTyul3KwM7aOFq3f9Y0SfMFKTfQJq45yYCMFZcwnvJSqDdUZVHffKcGcyj3N3mnIGMiU/3mbKH+xbCPn8f+HURembC9S4X+wtPHTHqhCWj2LAUDOgzdSvJ/C9o= root@squeeze"
end

Server 746d6ceeb76e05cfa2dea92a1c5753cd
	comment    "this is server1"
	label      mdtx1
	host       localhost
	lastCommit 2010-01-01,01:00:00 
	mdtxPort   11111
	sshPort    22
	wwwPort    443
	networks   www
	cacheSize  100 Mo
	cacheTTL   15 Day
	queryTTL   1 Week
	provide	  de5008799752552b7963a2670dc5eb18:391168=2.00
#	keys:
	userKey    "ssh-dss AAAAB3NzaC1kc3MAAACBANTUb46yvsV3bL8AX7oSg48oyN2MPqVCLWL8GiGADVzX71dZmYiqFeTJ5v3vBgk/7rEiaUzfAIZ0ebXhKB1TSc17Vqbdx2DfHm3/IbgBgrBe47VAkbPX+iW2n1zC9fBY5bc/819V0Szf7qvUyzZUkJ/9Vsi79Ikbq7rWu8r3VBeVAAAAFQDTyYPXMe1NzSrUHagG4BLlEQEx7QAAAIEAmYWtuhy0uuoLsoZu96ECnD6Se+buik4WhEi6xuAMPe+/RR7z3IHTh7Xvg56PyfqlFNReFnlc1s23ZZMmWsSAtNYFWqGrir/rddfisDm9Esk5aqPuwi8ToEFikGpthbJZYHjz4PpB2jfWDyLax2HpzFx4vmd1LcrCCM5PtuJ1sEAAAACBALPb55K2CZT3etbLgJ0rfoYDMnutNl38kK5rxf5Ps7Qfq2Uayv1BSKh8arOoMi94qoGKmBDLmwy99raNL4UhVly6YcnOPZ1yhVMfSGy2B1bFHIxh4qhxulm6VsVcPxIQpfwjQCRPImo57jkIjVk49o+K6DY7pDuy60MOmkXPr/sC mdtx@host"
	hostKey    "ssh-dss AAAAB3NzaC1kc3MAAACBANS+fcEeUJYXUH+58diSH8FsHQlj/3xjSVmEf5Od2ip87ro6ZSn3nJI1RR+ALqcLGn/K9fccl4Bj4Oq+M/6iMIL7ZQ6cAwzox9E0w0AjwQg+17WjWIfQNhycnuCCLcg6ThVobZ30RrNFcmwcXKKXP2CRS+eT6Ex8wC42uOEfMvQfAAAAFQDJYtWp9ZaxF1Ej/H0uu8Sqx+9dkQAAAIEAtrLXsPDqCvRwnGtusl1rlzjJCHYMJFZ5eAFDRCdNNUpGqHaHZpw9v8OIt6Qtvx6eVn97opVJ71FG9Xxpl17sIegh8/gprZZlK8ct9Lfs2YFOxcXv+i2r1dVHZwUkwSiYUE59Af71d+Os9VNStTj/U/GXtVNMS7NyqKoaWfFlItgAAACAevPvahBRDZbsjcfhf736q5vyEZbHau5s3VfSQci1u0rIekDhymTyul3KwM7aOFq3f9Y0SfMFKTfQJq45yYCMFZcwnvJSqDdUZVHffKcGcyj3N3mnIGMiU/3mbKH+xbCPn8f+HURembC9S4X+wtPHTHqhCWj2LAUDOgzdSvJ/C9o= root@squeeze"
end

# Local Variables:
# mode: conf
# mode: font-lock
# End:
[info openClose.c] steps: 0 / 0
[info confTree.c] Serializing configuration into: stdout
# This is the MediaTeX software configuration file.

# comment: greeter for this server
comment    "host1.mediatex.org configuration file"

# host: hostname used in urls
host       localhost

# port: listening port for incoming requests
mdtxPort   6560

# port: listening port for SSHd
sshPort    22

# port: listening ports for Apache
httpPort   80
httpsPort  443

# networks: networks the host belongs to
networks   www

# gateways: networks the host is a gateway for

# default cache parameters
cacheSize  100 Mo
cacheTTL   15 Day
queryTTL   1 Week

# local support parameters
checkTTL   6 Month
fileTTL    2 Month
suppTTL    5 Year
maxScore   10.00
badScore   1.00
powSupp    2.00
factSupp   2.00

# The below section is also managed by MediaTeX software.
# You should not edit by hand parameters bellow the -- line.
# (host fingerprint: f3e8a2cfcf01e5779608583de63cdc42)

Collection mdtx1-coll1@localhost:22
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
	share	  /HERE/misc/logoP2.iso,
		  SUPP11_logo.png,
		  SUPP21_logo.part1
end

Collection mdtx2-coll2@host2.mediatex.org:22
	cacheSize 200 Mo
	cacheTTL  1 Month
	queryTTL  15 Day
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
end

Collection mdtx3-coll3@host3.mediatex.org:33
	networks  private2
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
end
[notice utconf.c] *** Share a support:
[info supportFile.y] parse supports from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1/supports.txt
[info serverFile.y] parse coll3 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll3/servers.txt
[info confTree.c] configuration already expanded
[info confTree.c] configuration already populated
[info confTree.c] Serializing configuration into: stdout
# This is the MediaTeX software configuration file.

# comment: greeter for this server
comment    "host1.mediatex.org configuration file"

# host: hostname used in urls
host       localhost

# port: listening port for incoming requests
mdtxPort   6560

# port: listening port for SSHd
sshPort    22

# port: listening ports for Apache
httpPort   80
httpsPort  443

# networks: networks the host belongs to
networks   www

# gateways: networks the host is a gateway for

# default cache parameters
cacheSize  100 Mo
cacheTTL   15 Day
queryTTL   1 Week

# local support parameters
checkTTL   6 Month
fileTTL    2 Month
suppTTL    5 Year
maxScore   10.00
badScore   1.00
powSupp    2.00
factSupp   2.00

# The below section is also managed by MediaTeX software.
# You should not edit by hand parameters bellow the -- line.
# (host fingerprint: f3e8a2cfcf01e5779608583de63cdc42)

Collection mdtx1-coll1@localhost:22
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
	share	  /HERE/misc/logoP2.iso,
		  SUPP11_logo.png,
		  SUPP21_logo.part1
end

Collection mdtx2-coll2@host2.mediatex.org:22
	cacheSize 200 Mo
	cacheTTL  1 Month
	queryTTL  15 Day
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
end

Collection mdtx3-coll3@host3.mediatex.org:33
	networks  private2
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
	share	  SUPP21_logo.part1
end
[notice utconf.c] *** Share a support second time:
[notice confTree.c] support SUPP21_logo.part1 already added to collection coll3
[notice utconf.c] *** Share support with all collections:
[notice confTree.c] support SUPP21_logo.part1 already added to collection coll1
[info serverFile.y] parse coll1 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll1/servers.txt
[info serverFile.y] parse coll2 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll2/servers.txt
[notice confTree.c] support SUPP21_logo.part1 already added to collection coll3
[info confTree.c] configuration already expanded
[info confTree.c] configuration already populated
[info confTree.c] Serializing configuration into: stdout
# This is the MediaTeX software configuration file.

# comment: greeter for this server
comment    "host1.mediatex.org configuration file"

# host: hostname used in urls
host       localhost

# port: listening port for incoming requests
mdtxPort   6560

# port: listening port for SSHd
sshPort    22

# port: listening ports for Apache
httpPort   80
httpsPort  443

# networks: networks the host belongs to
networks   www

# gateways: networks the host is a gateway for

# default cache parameters
cacheSize  100 Mo
cacheTTL   15 Day
queryTTL   1 Week

# local support parameters
checkTTL   6 Month
fileTTL    2 Month
suppTTL    5 Year
maxScore   10.00
badScore   1.00
powSupp    2.00
factSupp   2.00

# The below section is also managed by MediaTeX software.
# You should not edit by hand parameters bellow the -- line.
# (host fingerprint: f3e8a2cfcf01e5779608583de63cdc42)

Collection mdtx1-coll1@localhost:22
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
	share	  /HERE/misc/logoP2.iso,
		  SUPP11_logo.png,
		  SUPP21_logo.part1
end

Collection mdtx2-coll2@host2.mediatex.org:22
	cacheSize 200 Mo
	cacheTTL  1 Month
	queryTTL  15 Day
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
	share	  SUPP21_logo.part1
end

Collection mdtx3-coll3@host3.mediatex.org:33
	networks  private2
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
	share	  SUPP21_logo.part1
end
[notice utconf.c] *** Withdraw a support:
[info confTree.c] configuration already expanded
[info confTree.c] configuration already populated
[info confTree.c] Serializing configuration into: stdout
# This is the MediaTeX software configuration file.

# comment: greeter for this server
comment    "host1.mediatex.org configuration file"

# host: hostname used in urls
host       localhost

# port: listening port for incoming requests
mdtxPort   6560

# port: listening port for SSHd
sshPort    22

# port: listening ports for Apache
httpPort   80
httpsPort  443

# networks: networks the host belongs to
networks   www

# gateways: networks the host is a gateway for

# default cache parameters
cacheSize  100 Mo
cacheTTL   15 Day
queryTTL   1 Week

# local support parameters
checkTTL   6 Month
fileTTL    2 Month
suppTTL    5 Year
maxScore   10.00
badScore   1.00
powSupp    2.00
factSupp   2.00

# The below section is also managed by MediaTeX software.
# You should not edit by hand parameters bellow the -- line.
# (host fingerprint: f3e8a2cfcf01e5779608583de63cdc42)

Collection mdtx1-coll1@localhost:22
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
	share	  /HERE/misc/logoP2.iso,
		  SUPP11_logo.png,
		  SUPP21_logo.part1
end

Collection mdtx2-coll2@host2.mediatex.org:22
	cacheSize 200 Mo
	cacheTTL  1 Month
	queryTTL  15 Day
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
	share	  SUPP21_logo.part1
end

Collection mdtx3-coll3@host3.mediatex.org:33
	networks  private2
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
end
[notice utconf.c] *** Withdraw second time:
[notice utconf.c] *** Withdraw support from all collections:
[info confTree.c] configuration already expanded
[info confTree.c] configuration already populated
[info confTree.c] Serializing configuration into: stdout
# This is the MediaTeX software configuration file.

# comment: greeter for this server
comment    "host1.mediatex.org configuration file"

# host: hostname used in urls
host       localhost

# port: listening port for incoming requests
mdtxPort   6560

# port: listening port for SSHd
sshPort    22

# port: listening ports for Apache
httpPort   80
httpsPort  443

# networks: networks the host belongs to
networks   www

# gateways: networks the host is a gateway for

# default cache parameters
cacheSize  100 Mo
cacheTTL   15 Day
queryTTL   1 Week

# local support parameters
checkTTL   6 Month
fileTTL    2 Month
suppTTL    5 Year
maxScore   10.00
badScore   1.00
powSupp    2.00
factSupp   2.00

# The below section is also managed by MediaTeX software.
# You should not edit by hand parameters bellow the -- line.
# (host fingerprint: f3e8a2cfcf01e5779608583de63cdc42)

Collection mdtx1-coll1@localhost:22
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
	share	  /HERE/misc/logoP2.iso,
		  SUPP11_logo.png
end

Collection mdtx2-coll2@host2.mediatex.org:22
	cacheSize 200 Mo
	cacheTTL  1 Month
	queryTTL  15 Day
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
end

Collection mdtx3-coll3@host3.mediatex.org:33
	networks  private2
	# --
	localhost 746d6ceeb76e05cfa2dea92a1c5753cd
end
[info confTree.c] free configuration
[info utconf.c] exit on success
