[info confFile.y] parse configuration from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1/mdtx1.conf
[info openClose.c] estimate 100 steps for load
[info openClose.c] parse coll1 collection ( SX )
[info serverFile.y] parse coll1 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll1/servers.txt
[info extractFile.y] parse coll1 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll1/extract000.txt
[info openClose.c] steps: 98 / 100
[info extractScore.c] local image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info extractScore.c]    7.50
[info extractScore.c]    9.00
[info extractScore.c] = 16.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  8.25
[info extractScore.c] local image score for de5008799752552b7963a2670dc5eb18:391168
[info extractScore.c]   10.00
[info extractScore.c]    2.00
[info extractScore.c] +  9.00
[info extractScore.c] = 21.00
[info extractScore.c] / 2
[info extractScore.c] > 10.00
[info extractScore.c] -------
[info extractScore.c] = 10.00
[info extractScore.c] local image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]    7.50
[info extractScore.c] =  7.50
[info extractScore.c] / 2
[info extractScore.c] -------
[info extractScore.c] =  3.75
[info extractScore.c]        archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]       container ISO/de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]      archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c] obsolete incoming archive: 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info extractScore.c]        archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]       container ISO/0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]      archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]     container CAT/1a167d608e76a6a4a8b16d168580873c:20480 = 3.75
[info extractScore.c]    archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]    archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]    archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]    archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]      archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]     container GZIP/3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]      archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]     container BZIP/fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info extractScore.c]    archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]    archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]    archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]    archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive 022a34b2f9b893fba5774237e1aa80ea:24075 = 8.25
[info extractScore.c]  archive 0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]  archive 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 = 3.75
[info extractScore.c]  archive 1a167d608e76a6a4a8b16d168580873c:20480 = 10.00
[info extractScore.c]  archive 3a04277dd1f43740a5fe17fd0ae9a5aa:24457 = 0.00
[info extractScore.c]  archive 65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]  archive 7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]   container TGZ/0387eee9820fa224525ff8b2e0dfa9be:24546 = 3.75
[info extractScore.c]   container TBZ/b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]   container AFIO/65f1464142f405dbbeeea4830c95ddd3:25600 = 0.00
[info extractScore.c]   container TAR/f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]   container CPIO/b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]   container ZIP/d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]   container RAR/7808473c7db9a9e3493a6b61f44f8805:20480 = 0.00
[info extractScore.c]  archive b281449c229bcc4a3556cdcc0d3ebcec:815 = 3.75
[info extractScore.c]  archive b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 = 0.00
[info extractScore.c]  archive b5810aba99ed0d15f1f0a073e646d5bd:25045 = 0.00
[info extractScore.c]  archive c0c055a0829982bd646e2fafff01aaa6:4066 = 3.75
[info extractScore.c]  archive d79581b67ec1932fd276dcf3b6d6db9a:24733 = 0.00
[info extractScore.c]  archive db8b80896f7202b656913f99d438075c:4090 = 0.00
[info extractScore.c]  archive de5008799752552b7963a2670dc5eb18:391168 = 10.00
[info extractScore.c]  archive f54fba7d2e070d48051ac3f8f1c2eb98:30720 = 0.00
[info extractScore.c]  archive fa2b0b536bf61f61617528c474e0bf61:24973 = 0.00
[info openClose.c] estimate 45 steps for load
[info openClose.c] parse coll1 collection ( SXC)
[info catalogFile.y] parse coll1 catalog from LOCALSTATEDIR/cache/mediatex/mdtx1/git/mdtx1-coll1/catalog000.txt
[info openClose.c] steps: 44 / 45
<!--#set var='HOME' value='../..' -->
<!--#include virtual='../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Server master </SPAN><SMALL>127.0.0.1</SMALL> (7.50)

<BR>
<SPAN  CLASS="textit">this is server2</SPAN>
<BR>
</P>

<P>
<UL>
<LI>fingerprint: <code>6b18ed0194b0fbadd08e0a13cccda00e</code></LI>
<LI>last commit: <code>2010-01-01,01:00:00</code></LI>
<LI>mdtx port: <code>6560</code></LI>
<LI>ssh port: <code>22</code></LI>
</UL>

</P>

<P>
On networks:
<UL>
<LI>private
</LI>
<LI>www
</LI>
</UL>

</P>

<P>
Gateway for:
<UL>
<LI>private
</LI>
</UL>

</P>

<P>
Provide images: 2
<UL>
<LI><code>022a34b2f9b893fba5774237e1aa80ea:24075 </code><A HREF="../archives/0000/000.shtml">(7.50)</A></LI>
<LI><code>de5008799752552b7963a2670dc5eb18:391168 </code><A HREF="../archives/0000/001.shtml">(10.00)</A></LI>
</UL>

</P>

<!--#include virtual='../../footer.html' -->
<!--#set var='HOME' value='../..' -->
<!--#include virtual='../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Server </SPAN><SMALL>LOCALHOST</SMALL> (2.00)

<BR>
<SPAN  CLASS="textit">this is server1</SPAN>
<BR>
</P>

<P>
<UL>
<LI>fingerprint: <code>746d6ceeb76e05cfa2dea92a1c5753cd</code></LI>
<LI>last commit: <code>2010-01-01,01:00:00</code></LI>
<LI>mdtx port: <code>11111</code></LI>
<LI>ssh port: <code>22</code></LI>
</UL>

</P>

<P>
On networks:
<UL>
<LI>www
</LI>
</UL>

</P>

<P>
Provide images: 1
<UL>
<LI><code>de5008799752552b7963a2670dc5eb18:391168 </code><A HREF="../archives/0000/001.shtml">(2.00)</A></LI>
</UL>

</P>

<!--#include virtual='../../footer.html' -->
<!--#set var='HOME' value='../..' -->
<!--#include virtual='../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Server </SPAN><SMALL>MEDIATEX.ORG</SMALL> (7.50)

<BR>
<SPAN  CLASS="textit">this is server3</SPAN>
<BR>
</P>

<P>
<UL>
<LI>fingerprint: <code>bedac32422739d7eced624ba20f5912e</code></LI>
<LI>last commit: <code>2010-01-01,01:00:00</code></LI>
<LI>mdtx port: <code>33333</code></LI>
<LI>ssh port: <code>2222</code></LI>
</UL>

</P>

<P>
On networks:
<UL>
<LI>private
</LI>
</UL>

</P>

<P>
Provide images: 3
<UL>
<LI><code>022a34b2f9b893fba5774237e1aa80ea:24075 </code><A HREF="../archives/0000/000.shtml">(9.00)</A></LI>
<LI><code>0a7ecd447ef2acb3b5c6e4c550e6636f:374784 </code><A HREF="../archives/0000/002.shtml">(7.50)</A></LI>
<LI><code>de5008799752552b7963a2670dc5eb18:391168 </code><A HREF="../archives/0000/001.shtml">(9.00)</A></LI>
</UL>

</P>

<!--#include virtual='../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>022a34b2f9b893fba5774237e1aa80ea:24075</code>
<BR><A HREF="../../../cgi/get.cgi?hash=022a34b2f9b893fba5774237e1aa80ea&size=24075">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (8.25)<UL>
<LI>format = PNG</LI>
</UL>

</P>

<P>

Catalog reference as documents:
<UL>
<LI><A HREF="../../../index/documents/0000/000.shtml">panthere</A></LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI><A HREF="../../servers/srv_6b18ed0194b0fbadd08e0a13cccda00e.shtml">127.0.0.1</A> (7.50)</LI>
<LI><A HREF="../../servers/srv_bedac32422739d7eced624ba20f5912e.shtml">mediatex.org</A> (9.00)</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>
<SPAN  CLASS="textit">logo/logo.png</SPAN> from TGZ <A HREF="../../archives/0000/006.shtml">(3.75)</A></LI>

<LI>
<SPAN  CLASS="textit">logo/logo.png</SPAN> from TBZ <A HREF="../../archives/0000/008.shtml">(0.00)</A></LI>

<LI>
<SPAN  CLASS="textit">logo/logo.png</SPAN> from AFIO <A HREF="../../archives/0000/009.shtml">(0.00)</A></LI>

<LI>
<SPAN  CLASS="textit">logo/logo.png</SPAN> from TAR <A HREF="../../archives/0000/010.shtml">(0.00)</A></LI>

<LI>
<SPAN  CLASS="textit">logo/logo.png</SPAN> from CPIO <A HREF="../../archives/0000/011.shtml">(0.00)</A></LI>

<LI>
<SPAN  CLASS="textit">logo/logo.png</SPAN> from ZIP <A HREF="../../archives/0000/013.shtml">(0.00)</A></LI>

<LI>
<SPAN  CLASS="textit">logo/logo.png</SPAN> from RAR (0.00)
<UL>
<LI>
<SPAN  CLASS="textit">part 1 </SPAN><A HREF="../../archives/0000/014.shtml">(0.00)</A></LI>
<LI>
<SPAN  CLASS="textit">part 2 </SPAN><A HREF="../../archives/0000/015.shtml">(0.00)</A></LI>
</UL>
</LI>

</UL>

</P>

<P>

Content: 0
<UL>
<LI>No content
</LI>
</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>0387eee9820fa224525ff8b2e0dfa9be:24546</code>
<BR><A HREF="../../../cgi/get.cgi?hash=0387eee9820fa224525ff8b2e0dfa9be&size=24546">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (3.75)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>
<SPAN  CLASS="textit">logo.tgz</SPAN> from CAT (3.75)
<UL>
<LI>
<SPAN  CLASS="textit">part 1 </SPAN><A HREF="../../archives/0000/005.shtml">(10.00)</A></LI>
<LI>
<SPAN  CLASS="textit">part 2 </SPAN><A HREF="../../archives/0000/004.shtml">(3.75)</A></LI>
</UL>
</LI>

</UL>

</P>

<P>

Content: 2
<UL>
<LI>TGZ (3.75)<UL>
<LI><A HREF="../../archives/0000/000.shtml">(8.25)</A> 
<SPAN  CLASS="textit">logo/logo.png</SPAN></LI>
<LI><A HREF="../../archives/0000/007.shtml">(3.75)</A> 
<SPAN  CLASS="textit">logo/logo.xpm</SPAN></LI>
</UL>
</LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>0a7ecd447ef2acb3b5c6e4c550e6636f:374784</code>
<BR><A HREF="../../../cgi/get.cgi?hash=0a7ecd447ef2acb3b5c6e4c550e6636f&size=374784">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (3.75)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI><A HREF="../../servers/srv_bedac32422739d7eced624ba20f5912e.shtml">mediatex.org</A> (7.50)</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>Cache: uploaded on 1994-01-01 00:00:00</LI>
</UL>

</P>

<P>

Content: 1
<UL>
<LI>ISO <A HREF="../../archives/0000/004.shtml">(3.75)</A> 
<SPAN  CLASS="textit">logoP2.cat</SPAN></LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>1a167d608e76a6a4a8b16d168580873c:20480</code>
<BR><A HREF="../../../cgi/get.cgi?hash=1a167d608e76a6a4a8b16d168580873c&size=20480">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (10.00)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>
<SPAN  CLASS="textit">logoP1.cat</SPAN> from ISO <A HREF="../../archives/0000/001.shtml">(10.00)</A></LI>

</UL>

</P>

<P>

Content: 1
<UL>
<LI>CAT <A HREF="../../archives/0000/006.shtml">(3.75)</A> 
<SPAN  CLASS="textit">logo.tgz</SPAN></LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>3a04277dd1f43740a5fe17fd0ae9a5aa:24457</code>
<BR><A HREF="../../../cgi/get.cgi?hash=3a04277dd1f43740a5fe17fd0ae9a5aa&size=24457">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (0.00)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>External source</LI>
</UL>

</P>

<P>

Content: 1
<UL>
<LI>GZIP <A HREF="../../archives/0000/011.shtml">(0.00)</A> 
<SPAN  CLASS="textit">logo.cpio</SPAN></LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>65f1464142f405dbbeeea4830c95ddd3:25600</code>
<BR><A HREF="../../../cgi/get.cgi?hash=65f1464142f405dbbeeea4830c95ddd3&size=25600">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (0.00)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>External source</LI>
</UL>

</P>

<P>

Content: 2
<UL>
<LI>AFIO (0.00)<UL>
<LI><A HREF="../../archives/0000/000.shtml">(8.25)</A> 
<SPAN  CLASS="textit">logo/logo.png</SPAN></LI>
<LI><A HREF="../../archives/0000/007.shtml">(3.75)</A> 
<SPAN  CLASS="textit">logo/logo.xpm</SPAN></LI>
</UL>
</LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>7808473c7db9a9e3493a6b61f44f8805:20480</code>
<BR><A HREF="../../../cgi/get.cgi?hash=7808473c7db9a9e3493a6b61f44f8805&size=20480">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (0.00)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>External source</LI>
</UL>

</P>

<P>

Content: 2
<UL>
<LI>RAR (0.00)<UL>
<LI><A HREF="../../archives/0000/000.shtml">(8.25)</A> 
<SPAN  CLASS="textit">logo/logo.png</SPAN></LI>
<LI><A HREF="../../archives/0000/007.shtml">(3.75)</A> 
<SPAN  CLASS="textit">logo/logo.xpm</SPAN></LI>
</UL>
</LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>b281449c229bcc4a3556cdcc0d3ebcec:815</code>
<BR><A HREF="../../../cgi/get.cgi?hash=b281449c229bcc4a3556cdcc0d3ebcec&size=815">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (3.75)<UL>
<LI>format = XPM</LI>
<LI>licence = GPLv3</LI>
</UL>

</P>

<P>

Catalog reference as documents:
<UL>
<LI><A HREF="../../../index/documents/0000/000.shtml">panthere</A></LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>
<SPAN  CLASS="textit">logo/logo.xpm</SPAN> from TGZ <A HREF="../../archives/0000/006.shtml">(3.75)</A></LI>

<LI>
<SPAN  CLASS="textit">logo/logo.xpm</SPAN> from TBZ <A HREF="../../archives/0000/008.shtml">(0.00)</A></LI>

<LI>
<SPAN  CLASS="textit">logo/logo.xpm</SPAN> from AFIO <A HREF="../../archives/0000/009.shtml">(0.00)</A></LI>

<LI>
<SPAN  CLASS="textit">logo/logo.xpm</SPAN> from TAR <A HREF="../../archives/0000/010.shtml">(0.00)</A></LI>

<LI>
<SPAN  CLASS="textit">logo/logo.xpm</SPAN> from CPIO <A HREF="../../archives/0000/011.shtml">(0.00)</A></LI>

<LI>
<SPAN  CLASS="textit">logo/logo.xpm</SPAN> from ZIP <A HREF="../../archives/0000/013.shtml">(0.00)</A></LI>

<LI>
<SPAN  CLASS="textit">logo/logo.xpm</SPAN> from RAR (0.00)
<UL>
<LI>
<SPAN  CLASS="textit">part 1 </SPAN><A HREF="../../archives/0000/014.shtml">(0.00)</A></LI>
<LI>
<SPAN  CLASS="textit">part 2 </SPAN><A HREF="../../archives/0000/015.shtml">(0.00)</A></LI>
</UL>
</LI>

</UL>

</P>

<P>

Content: 0
<UL>
<LI>No content
</LI>
</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088</code>
<BR><A HREF="../../../cgi/get.cgi?hash=b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5&size=25088">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (0.00)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>
<SPAN  CLASS="textit">logo.cpio</SPAN> from GZIP <A HREF="../../archives/0000/003.shtml">(0.00)</A></LI>

<LI>
<SPAN  CLASS="textit">logo.cpio</SPAN> from BZIP <A HREF="../../archives/0000/012.shtml">(0.00)</A></LI>

</UL>

</P>

<P>

Content: 2
<UL>
<LI>CPIO (0.00)<UL>
<LI><A HREF="../../archives/0000/000.shtml">(8.25)</A> 
<SPAN  CLASS="textit">logo/logo.png</SPAN></LI>
<LI><A HREF="../../archives/0000/007.shtml">(3.75)</A> 
<SPAN  CLASS="textit">logo/logo.xpm</SPAN></LI>
</UL>
</LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>b5810aba99ed0d15f1f0a073e646d5bd:25045</code>
<BR><A HREF="../../../cgi/get.cgi?hash=b5810aba99ed0d15f1f0a073e646d5bd&size=25045">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (0.00)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>External source</LI>
</UL>

</P>

<P>

Content: 2
<UL>
<LI>TBZ (0.00)<UL>
<LI><A HREF="../../archives/0000/000.shtml">(8.25)</A> 
<SPAN  CLASS="textit">logo/logo.png</SPAN></LI>
<LI><A HREF="../../archives/0000/007.shtml">(3.75)</A> 
<SPAN  CLASS="textit">logo/logo.xpm</SPAN></LI>
</UL>
</LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>c0c055a0829982bd646e2fafff01aaa6:4066</code>
<BR><A HREF="../../../cgi/get.cgi?hash=c0c055a0829982bd646e2fafff01aaa6&size=4066">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (3.75)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>
<SPAN  CLASS="textit">logoP2.cat</SPAN> from ISO <A HREF="../../archives/0000/002.shtml">(3.75)</A></LI>

</UL>

</P>

<P>

Content: 1
<UL>
<LI>CAT <A HREF="../../archives/0000/006.shtml">(3.75)</A> 
<SPAN  CLASS="textit">logo.tgz</SPAN></LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>d79581b67ec1932fd276dcf3b6d6db9a:24733</code>
<BR><A HREF="../../../cgi/get.cgi?hash=d79581b67ec1932fd276dcf3b6d6db9a&size=24733">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (0.00)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>External source</LI>
</UL>

</P>

<P>

Content: 2
<UL>
<LI>ZIP (0.00)<UL>
<LI><A HREF="../../archives/0000/000.shtml">(8.25)</A> 
<SPAN  CLASS="textit">logo/logo.png</SPAN></LI>
<LI><A HREF="../../archives/0000/007.shtml">(3.75)</A> 
<SPAN  CLASS="textit">logo/logo.xpm</SPAN></LI>
</UL>
</LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>db8b80896f7202b656913f99d438075c:4090</code>
<BR><A HREF="../../../cgi/get.cgi?hash=db8b80896f7202b656913f99d438075c&size=4090">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (0.00)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>External source</LI>
</UL>

</P>

<P>

Content: 2
<UL>
<LI>RAR (0.00)<UL>
<LI><A HREF="../../archives/0000/000.shtml">(8.25)</A> 
<SPAN  CLASS="textit">logo/logo.png</SPAN></LI>
<LI><A HREF="../../archives/0000/007.shtml">(3.75)</A> 
<SPAN  CLASS="textit">logo/logo.xpm</SPAN></LI>
</UL>
</LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>de5008799752552b7963a2670dc5eb18:391168</code>
<BR><A HREF="../../../cgi/get.cgi?hash=de5008799752552b7963a2670dc5eb18&size=391168">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (10.00)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI><A HREF="../../servers/srv_6b18ed0194b0fbadd08e0a13cccda00e.shtml">127.0.0.1</A> (10.00)</LI>
<LI><A HREF="../../servers/srv_746d6ceeb76e05cfa2dea92a1c5753cd.shtml">localhost</A> (2.00)</LI>
<LI><A HREF="../../servers/srv_bedac32422739d7eced624ba20f5912e.shtml">mediatex.org</A> (9.00)</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>Cache: uploaded on 2010-01-01 01:00:00</LI>
</UL>

</P>

<P>

Content: 1
<UL>
<LI>ISO <A HREF="../../archives/0000/005.shtml">(10.00)</A> 
<SPAN  CLASS="textit">logoP1.cat</SPAN></LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>f54fba7d2e070d48051ac3f8f1c2eb98:30720</code>
<BR><A HREF="../../../cgi/get.cgi?hash=f54fba7d2e070d48051ac3f8f1c2eb98&size=30720">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (0.00)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>External source</LI>
</UL>

</P>

<P>

Content: 2
<UL>
<LI>TAR (0.00)<UL>
<LI><A HREF="../../archives/0000/000.shtml">(8.25)</A> 
<SPAN  CLASS="textit">logo/logo.png</SPAN></LI>
<LI><A HREF="../../archives/0000/007.shtml">(3.75)</A> 
<SPAN  CLASS="textit">logo/logo.xpm</SPAN></LI>
</UL>
</LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Record:</SPAN><code>fa2b0b536bf61f61617528c474e0bf61:24973</code>
<BR><A HREF="../../../cgi/get.cgi?hash=fa2b0b536bf61f61617528c474e0bf61&size=24973">
<IMG BORDER="0" SRC="../../../icons/floppy-icon.png" ALT="download"/>
</A> (0.00)
</P>

<P>

Catalog reference as documents:
<UL>
<LI>Not in catalog
</LI>
</UL>

</P>

<P>

Provided by servers:
<UL>
<LI>Is not an image
</LI>
</UL>

</P>

<P>

Comes from:
<UL>
<LI>External source</LI>
</UL>

</P>

<P>

Content: 1
<UL>
<LI>BZIP <A HREF="../../archives/0000/011.shtml">(0.00)</A> 
<SPAN  CLASS="textit">logo.cpio</SPAN></LI>

</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">All archives</SPAN> : 16
<BR>
</P>
<!--#include virtual='../header.shtml' -->
<P>
<UL>
<LI><code>022a34b2f9b893fba5774237e1aa80ea:24075 </code><A HREF="../../archives/0000/000.shtml">(8.25)</A></LI>
<LI><code>0387eee9820fa224525ff8b2e0dfa9be:24546 </code><A HREF="../../archives/0000/006.shtml">(3.75)</A></LI>
<LI><code>0a7ecd447ef2acb3b5c6e4c550e6636f:374784 </code><A HREF="../../archives/0000/002.shtml">(3.75)</A></LI>
<LI><code>1a167d608e76a6a4a8b16d168580873c:20480 </code><A HREF="../../archives/0000/005.shtml">(10.00)</A></LI>
<LI><code>3a04277dd1f43740a5fe17fd0ae9a5aa:24457 </code><A HREF="../../archives/0000/003.shtml">(0.00)</A></LI>
<LI><code>65f1464142f405dbbeeea4830c95ddd3:25600 </code><A HREF="../../archives/0000/009.shtml">(0.00)</A></LI>
<LI><code>7808473c7db9a9e3493a6b61f44f8805:20480 </code><A HREF="../../archives/0000/014.shtml">(0.00)</A></LI>
<LI><code>b281449c229bcc4a3556cdcc0d3ebcec:815 </code><A HREF="../../archives/0000/007.shtml">(3.75)</A></LI>
<LI><code>b34bb9bf9ae4ec5b4a5bc2ab3e2a18c5:25088 </code><A HREF="../../archives/0000/011.shtml">(0.00)</A></LI>
<LI><code>b5810aba99ed0d15f1f0a073e646d5bd:25045 </code><A HREF="../../archives/0000/008.shtml">(0.00)</A></LI>
<LI><code>c0c055a0829982bd646e2fafff01aaa6:4066 </code><A HREF="../../archives/0000/004.shtml">(3.75)</A></LI>
<LI><code>d79581b67ec1932fd276dcf3b6d6db9a:24733 </code><A HREF="../../archives/0000/013.shtml">(0.00)</A></LI>
<LI><code>db8b80896f7202b656913f99d438075c:4090 </code><A HREF="../../archives/0000/015.shtml">(0.00)</A></LI>
<LI><code>de5008799752552b7963a2670dc5eb18:391168 </code><A HREF="../../archives/0000/001.shtml">(10.00)</A></LI>
<LI><code>f54fba7d2e070d48051ac3f8f1c2eb98:30720 </code><A HREF="../../archives/0000/010.shtml">(0.00)</A></LI>
<LI><code>fa2b0b536bf61f61617528c474e0bf61:24973 </code><A HREF="../../archives/0000/012.shtml">(0.00)</A></LI>
</UL>

</P>

<!--#include virtual='../../../footer.html' -->
[info extractScore.c] extraction score = 0.00
[emerg extractScore.c] coll1 collection: Perenniality lost (0.00)
<!--#set var='HOME' value='../../..' -->
<!--#include virtual='../../scoreHeader.shtml' -->

<P>

<SPAN  CLASS="textbf">Bad images</SPAN> : 9
<BR>
<SPAN  CLASS="textit">Perenniality lost</SPAN>
<BR>
</P>
541 Ko
should be burned into supports:<!--#include virtual='../header.shtml' -->
<P>
<UL>
<LI><code>3a04277dd1f43740a5fe17fd0ae9a5aa:24457 </code><A HREF="../../archives/0000/003.shtml">(0.00)</A></LI>
<LI><code>65f1464142f405dbbeeea4830c95ddd3:25600 </code><A HREF="../../archives/0000/009.shtml">(0.00)</A></LI>
<LI><code>7808473c7db9a9e3493a6b61f44f8805:20480 </code><A HREF="../../archives/0000/014.shtml">(0.00)</A></LI>
<LI><code>b5810aba99ed0d15f1f0a073e646d5bd:25045 </code><A HREF="../../archives/0000/008.shtml">(0.00)</A></LI>
<LI><code>d79581b67ec1932fd276dcf3b6d6db9a:24733 </code><A HREF="../../archives/0000/013.shtml">(0.00)</A></LI>
<LI><code>db8b80896f7202b656913f99d438075c:4090 </code><A HREF="../../archives/0000/015.shtml">(0.00)</A></LI>
<LI><code>f54fba7d2e070d48051ac3f8f1c2eb98:30720 </code><A HREF="../../archives/0000/010.shtml">(0.00)</A></LI>
<LI><code>fa2b0b536bf61f61617528c474e0bf61:24973 </code><A HREF="../../archives/0000/012.shtml">(0.00)</A></LI>
<LI><code>0a7ecd447ef2acb3b5c6e4c550e6636f:374784 </code><A HREF="../../archives/0000/002.shtml">(3.75)</A></LI>
</UL>

</P>

<!--#include virtual='../../../footer.html' -->
<!--#set var='HOME' value='..' -->
<!--#include virtual='../scoreHeader.shtml' -->

<P>

Score parameters:
<UL>
<LI>serverTTL : 2 Week
</LI>
<LI>uploadTTL : 1 Month
</LI>
<LI>suppTTL   : 5 Year
</LI>
<LI>maxScore  : 10.00
</LI>
<LI>badScore  : 1.00
</LI>
<LI>powSupp   : 2.00
</LI>
<LI>factSupp  : 2.00
</LI>
<LI>fileScore : 10.00
</LI>
<LI>minGeoDup : 2</LI>
</UL>

</P>

<P>

Self-ingestion parameters:
<UL>
<LI>logApache : no</LI>
<LI>logCvs    : no</LI>
<LI>logAudit  : no</LI>
</UL>

</P>

<P>

All images: 3
<UL>
<LI><code>022a34b2f9b893fba5774237e1aa80ea:24075 </code><A HREF="archives/0000/000.shtml">(8.25)</A></LI>
<LI><code>0a7ecd447ef2acb3b5c6e4c550e6636f:374784 </code><A HREF="archives/0000/002.shtml">(3.75)</A></LI>
<LI><code>de5008799752552b7963a2670dc5eb18:391168 </code><A HREF="archives/0000/001.shtml">(10.00)</A></LI>
</UL>

</P>

<!--#include virtual='../footer.html' -->
<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.1//EN'>

<!--Inspired from LaTeX2HTML 2008 (1.71).
 Generated by MediaTeX software.
 MediaTex is an Electronic Records Management System.
 Copyright (C) 2014 2015 2016 Nicolas Roche -->
<HTML>
<HEAD>
<TITLE>Score</TITLE>
<META NAME='description' CONTENT='MediaTeX catalog'>
<META NAME='keywords' CONTENT='Score'>
<META NAME='resource-type' CONTENT='data files'>
<META NAME='distribution' CONTENT='private content'>

<META HTTP-EQUIV='Content-Type' CONTENT='text/html; charset=utf-8'>
<META NAME='Generator' CONTENT='MediaTeX v2013'>
<META HTTP-EQUIV='Content-Style-Type' CONTENT='text/css'>

<LINK REL='STYLESHEET' HREF='<!--#echo var='HOME' -->/mediatex.css'>
<LINK REL='icon' TYPE='image/png' HREF='<!--#echo var='HOME' -->/logo'>

</HEAD>

<BODY >
<TABLE CELLPADDING=3>
<TR><TD ALIGN='LEFT' VALIGN='TOP' WIDTH=192><TABLE  WIDTH='100%'>
<TR><TD>
<A NAME='mdtx1'
HREF='https://dns_name.org:80/~mdtx2-coll1/score'><IMG
ALIGN='BOTTOM' BORDER='0' SRC='<!--#echo var='HOME' -->/logo'
ALT='top'></A>
<P>
(0.00)

<BR><A HREF="<!--#echo var='HOME' -->/score/lists/0000/000.shtml">All archives</A>
<BR><A HREF="<!--#echo var='HOME' -->/score/badLists/0000/000.shtml">Bad images</A>
<BR><UL>
<LI><A HREF="<!--#echo var='HOME' -->/score/servers/srv_6b18ed0194b0fbadd08e0a13cccda00e.shtml">127.0.0.1</A></LI>
<LI><A HREF="<!--#echo var='HOME' -->/score/servers/srv_746d6ceeb76e05cfa2dea92a1c5753cd.shtml">localhost</A></LI>
<LI><A HREF="<!--#echo var='HOME' -->/score/servers/srv_bedac32422739d7eced624ba20f5912e.shtml">mediatex.org</A></LI>
</UL>

<P>
</TD></TR>
</TABLE></TD>
<TD ALIGN='LEFT' VALIGN='TOP'><TABLE>
<TR><TD>
<TABLE CELLPADDING=3>
<TR><TD ALIGN='CENTER'><A NAME='mdtx7'
HREF='<!--#echo var='HOME' -->/index'>Index</A></TD>
<TD ALIGN='CENTER'><A NAME='mdtx8'
HREF='<!--#echo var='HOME' -->/cache'>Cache</A></TD>
<TD ALIGN='CENTER'><A NAME='mdtx9'
HREF='<!--#echo var='HOME' -->/score'>Score</A></TD>
<TD ALIGN='CENTER'><A NAME='mdtx10'
HREF='<!--#echo var='HOME' -->/cgi/cgit.cgi/.git/'>Version</A></TD>
</TR>
</TABLE>
<DIV ALIGN='CENTER'>

</DIV>

[info confTree.c] free configuration
[info utextractHtml.c] exit on success
