[info serv.c] client ipc key: {LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1/mdtx1.conf, 6562}
[notice utserv.c] please send me HUP, USR1 or TERM signals:
[notice utserv.c] *** upgrade:
[info confFile.y] parse configuration from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1/mdtx1.conf
[info openClose.c] callUpdate mdtx1-coll1
[info openClose.c] estimate 137 steps for load
[info openClose.c] parse coll1 collection ( SXC)
[info serverFile.y] parse coll1 servers from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll1/servers.txt
[info supportFile.y] parse supports from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1/supports.txt
[info upgrade.c] compute support score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784 (/HERE/misc/logoP2.iso)
[info upgrade.c] file: = 10.00
[info upgrade.c] compute support score for 022a34b2f9b893fba5774237e1aa80ea:24075 (SUPP11_logo.png)
[warning upgrade.c] "SUPP11_logo.png" support have expired since 12784 days
[info upgrade.c] compute support score for de5008799752552b7963a2670dc5eb18:391168 (SUPP21_logo.part1)
[info upgrade.c] laps > suppTTL: (1 / (1 + 2.00 * (1.00)) ) * 1.00 = 0.33
[info upgrade.c] compute image score for 022a34b2f9b893fba5774237e1aa80ea:24075
[info upgrade.c]    0.00
[info upgrade.c] -------
[info upgrade.c] =  0.00
[info upgrade.c] compute image score for 0a7ecd447ef2acb3b5c6e4c550e6636f:374784
[info upgrade.c]   10.00
[info upgrade.c] -------
[info upgrade.c] = 10.00
[info upgrade.c] compute image score for de5008799752552b7963a2670dc5eb18:391168
[info upgrade.c]    0.33
[info upgrade.c] -------
[info upgrade.c] =  0.33
[info extractFile.y] parse coll1 extraction data from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll1/extract000.txt
[info catalogFile.y] parse coll1 catalog from LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1-coll1/catalog000.txt
[info openClose.c] steps: 137 / 137
[notice utserv.c] *** refuse to del localhost key: 
[info serv.c] del 746d6ceeb76e05cfa2dea92a1c5753cd key from coll1 collection
[warning serv.c] key "746d6ceeb76e05cfa2dea92a1c5753cd" is our coll1 collection key
[err serv.c] cannot del 746d6ceeb76e05cfa2dea92a1c5753cd key to coll1 collection
[notice utserv.c] *** del a key: 
[info serv.c] del bedac32422739d7eced624ba20f5912e key from coll1 collection
[info ssh.c] Serializing the authorized_keys file: LOCALSTATEDIR/cache/mediatex/mdtx1/home/mdtx1-coll1/.ssh/authorized_keys
# This file is managed by MediaTeX software.
ssh-dss AAAAB3NzaC1kc3MAAACBANTUb46yvsV3bL8AX7oSg48oyN2MPqVCLWL8GiGADVzX71dZmYiqFeTJ5v3vBgk/7rEiaUzfAIZ0ebXhKB1TSc17Vqbdx2DfHm3/IbgBgrBe47VAkbPX+iW2n1zC9fBY5bc/819V0Szf7qvUyzZUkJ/9Vsi79Ikbq7rWu8r3VBeVAAAAFQDTyYPXMe1NzSrUHagG4BLlEQEx7QAAAIEAmYWtuhy0uuoLsoZu96ECnD6Se+buik4WhEi6xuAMPe+/RR7z3IHTh7Xvg56PyfqlFNReFnlc1s23ZZMmWsSAtNYFWqGrir/rddfisDm9Esk5aqPuwi8ToEFikGpthbJZYHjz4PpB2jfWDyLax2HpzFx4vmd1LcrCCM5PtuJ1sEAAAACBALPb55K2CZT3etbLgJ0rfoYDMnutNl38kK5rxf5Ps7Qfq2Uayv1BSKh8arOoMi94qoGKmBDLmwy99raNL4UhVly6YcnOPZ1yhVMfSGy2B1bFHIxh4qhxulm6VsVcPxIQpfwjQCRPImo57jkIjVk49o+K6DY7pDuy60MOmkXPr/sC mdtx@host
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDlnF3vIn3ad3kMTMdqLa/Q7WK0F2Lm1LbUPTh58ZYcCevtB0Eh4nyEuglApyu0d44/PfcUBAUEBVn3TOwPH6PIU0s7UmiiZpNHSO1cRWuULts8ebE2ePPbKiNj8rcqmTTuoxXB3nnbWtbqJAu4ld6s1P5Rtm84B53dltlkZijCbtBa3FFPpShiRJQ8mIdQBKn5GXg5FDZ6xj9DUVcWAYxmkZXH3Wa2Uy1fSGMhhvSkvzDWJI/m3bBcQQZVJzrrr3Z+KG4MxO2qe1IhOa5Vjlf20PdRy0oB25NU09OfeV+LhfEdDadWvf2lRvcR60RhAf9C4GJOtRSjpO2xo8FNBnjB
[info ssh.c] Serializing the ssh's config file: LOCALSTATEDIR/cache/mediatex/mdtx1/home/mdtx1-coll1/.ssh/config
# This file is managed by MediaTeX software.

# Do not ask for password
BatchMode yes
Compression yes
#LogLevel DEBUG3

Host 127.0.0.1
	Port 22

Host localhost
	Port 22

[info confTree.c] configuration already populated
[info ssh.c] Serializing the known_host file: LOCALSTATEDIR/cache/mediatex/mdtx1/home/mdtx1-coll1/.ssh/known_hosts
[warning ssh.c] Please avoid using localhost in the configuration
[warning ssh.c] Please avoid having localhost in the servers list
# This file is managed by MediaTeX software.
localhost ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzupGWlTD1QFcjkNoqyWuAMBo386WHH+B/EVs1pNYBd8NrHvTvFeuvDxOBwIYkI4T7ak0wXLtbW9o0KV2EPtrlGwMelVbM+X4nxXrXtDk5B6Zl0tcPu1NLwHRwhzh8reNXuEqLHE5EfPM1Z8B1eYNoiMEXdCXKzb8dlDXgIe/cjkrS5vJSKicMxb62W2cK9e5I62x+paAQDaDAznvqNFMBXZy/S8t9sqh0CL5ww4+pDXhA9PCdob7EOSA9e4EzgXTMiyyU8Z7gqSqq9DwH4fxiENJLzGbD2e+VM9iPQqp0gI9/4Xn1ZX1x12ddFenAYkLjIZCf8BBAJZRq5WeTwr1B
127.0.0.1 ssh-dss AAAAB3NzaC1kc3MAAACBANS+fcEeUJYXUH+58diSH8FsHQlj/3xjSVmEf5Od2ip87ro6ZSn3nJI1RR+ALqcLGn/K9fccl4Bj4Oq+M/6iMIL7ZQ6cAwzox9E0w0AjwQg+17WjWIfQNhycnuCCLcg6ThVobZ30RrNFcmwcXKKXP2CRS+eT6Ex8wC42uOEfMvQfAAAAFQDJYtWp9ZaxF1Ej/H0uu8Sqx+9dkQAAAIEAtrLXsPDqCvRwnGtusl1rlzjJCHYMJFZ5eAFDRCdNNUpGqHaHZpw9v8OIt6Qtvx6eVn97opVJ71FG9Xxpl17sIegh8/gprZZlK8ct9Lfs2YFOxcXv+i2r1dVHZwUkwSiYUE59Af71d+Os9VNStTj/U/GXtVNMS7NyqKoaWfFlItgAAACAevPvahBRDZbsjcfhf736q5vyEZbHau5s3VfSQci1u0rIekDhymTyul3KwM7aOFq3f9Y0SfMFKTfQJq45yYCMFZcwnvJSqDdUZVHffKcGcyj3N3mnIGMiU/3mbKH+xbCPn8f+HURembC9S4X+wtPHTHqhCWj2LAUDOgzdSvJ/C9o= root@squeeze
localhost ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzupGWlTD1QFcjkNoqyWuAMBo386WHH+B/EVs1pNYBd8NrHvTvFeuvDxOBwIYkI4T7ak0wXLtbW9o0KV2EPtrlGwMelVbM+X4nxXrXtDk5B6Zl0tcPu1NLwHRwhzh8reNXuEqLHE5EfPM1Z8B1eYNoiMEXdCXKzb8dlDXgIe/cjkrS5vJSKicMxb62W2cK9e5I62x+paAQDaDAznvqNFMBXZy/S8t9sqh0CL5ww4+pDXhA9PCdob7EOSA9e4EzgXTMiyyU8Z7gqSqq9DwH4fxiENJLzGbD2e+VM9iPQqp0gI9/4Xn1ZX1x12ddFenAYkLjIZCf8BBAJZRq5WeTwr1B
[notice utserv.c] *** refuse to add localhost key: 
[info serv.c] add client/user1Key_rsa.pub key to coll1 collection
[warning serv.c] key "746d6ceeb76e05cfa2dea92a1c5753cd" is our coll1 collection key
[err serv.c] cannot add client/user1Key_rsa.pub key to coll1 collection
[notice utserv.c] *** add a key: 
[info serv.c] add client/user3Key_dsa.pub key to coll1 collection
[info ssh.c] Serializing the authorized_keys file: LOCALSTATEDIR/cache/mediatex/mdtx1/home/mdtx1-coll1/.ssh/authorized_keys
# This file is managed by MediaTeX software.
ssh-dss AAAAB3NzaC1kc3MAAACBANTUb46yvsV3bL8AX7oSg48oyN2MPqVCLWL8GiGADVzX71dZmYiqFeTJ5v3vBgk/7rEiaUzfAIZ0ebXhKB1TSc17Vqbdx2DfHm3/IbgBgrBe47VAkbPX+iW2n1zC9fBY5bc/819V0Szf7qvUyzZUkJ/9Vsi79Ikbq7rWu8r3VBeVAAAAFQDTyYPXMe1NzSrUHagG4BLlEQEx7QAAAIEAmYWtuhy0uuoLsoZu96ECnD6Se+buik4WhEi6xuAMPe+/RR7z3IHTh7Xvg56PyfqlFNReFnlc1s23ZZMmWsSAtNYFWqGrir/rddfisDm9Esk5aqPuwi8ToEFikGpthbJZYHjz4PpB2jfWDyLax2HpzFx4vmd1LcrCCM5PtuJ1sEAAAACBALPb55K2CZT3etbLgJ0rfoYDMnutNl38kK5rxf5Ps7Qfq2Uayv1BSKh8arOoMi94qoGKmBDLmwy99raNL4UhVly6YcnOPZ1yhVMfSGy2B1bFHIxh4qhxulm6VsVcPxIQpfwjQCRPImo57jkIjVk49o+K6DY7pDuy60MOmkXPr/sC mdtx@host
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDlnF3vIn3ad3kMTMdqLa/Q7WK0F2Lm1LbUPTh58ZYcCevtB0Eh4nyEuglApyu0d44/PfcUBAUEBVn3TOwPH6PIU0s7UmiiZpNHSO1cRWuULts8ebE2ePPbKiNj8rcqmTTuoxXB3nnbWtbqJAu4ld6s1P5Rtm84B53dltlkZijCbtBa3FFPpShiRJQ8mIdQBKn5GXg5FDZ6xj9DUVcWAYxmkZXH3Wa2Uy1fSGMhhvSkvzDWJI/m3bBcQQZVJzrrr3Z+KG4MxO2qe1IhOa5Vjlf20PdRy0oB25NU09OfeV+LhfEdDadWvf2lRvcR60RhAf9C4GJOtRSjpO2xo8FNBnjB
ssh-dss AAAAB3NzaC1kc3MAAACBALSNj2g79yICAQHQBrEWzwYp/h7KGJl7KPOkRcgyr1vyBhBYfJJQpxhKZOBLkFs4RoyZmx+NX3tMUNH2FkYPbSWjms1czokhM9nq96ZUGCx/rWZ2oDB5KVNx+sp8rqveTDB45FTfJQ6+2PDoHfajc6kthxM/UUTBzTLaTD5V1ChjAAAAFQCfhKdnRBlZEnyp5U4w+xqJLg/yPwAAAIEAp6SRRiF6ucA+NZ+GxsBBgQMKT/uokI7rxWnljPeyVbAi3c07mdpEoLUDAUbAy4qfatWXEf9RDLGQuFwyMeBkMtRHENmuWyIlRT191xhQzKMAhbFukRNdmjm7lvB9gnlhPiESxmrZqBppeKh13CtntWQyEL8KYv5AVoEwfkwGyGMAAACAAW8BloIq4V7j4/qEJWjvlHUbVHlgeZU9gnOSL2BDaS1zqTYrUTuWo/HKRMWf6xWbh1Es7YpYtQ8EA8Z/fW4xGSH1J+nhCNxepezXNAzejPF/aHph9YcPp7n6qdW0dHoL6GfPJt47Rs+XyXalEiyNU1POm38qn3/BKuHisS49/0o=
[info ssh.c] Serializing the ssh's config file: LOCALSTATEDIR/cache/mediatex/mdtx1/home/mdtx1-coll1/.ssh/config
# This file is managed by MediaTeX software.

# Do not ask for password
BatchMode yes
Compression yes
#LogLevel DEBUG3

Host 127.0.0.1
	Port 22

Host localhost
	Port 22

[info confTree.c] configuration already populated
[info ssh.c] Serializing the known_host file: LOCALSTATEDIR/cache/mediatex/mdtx1/home/mdtx1-coll1/.ssh/known_hosts
[warning ssh.c] Please avoid using localhost in the configuration
[warning ssh.c] Please avoid having localhost in the servers list
# This file is managed by MediaTeX software.
localhost ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzupGWlTD1QFcjkNoqyWuAMBo386WHH+B/EVs1pNYBd8NrHvTvFeuvDxOBwIYkI4T7ak0wXLtbW9o0KV2EPtrlGwMelVbM+X4nxXrXtDk5B6Zl0tcPu1NLwHRwhzh8reNXuEqLHE5EfPM1Z8B1eYNoiMEXdCXKzb8dlDXgIe/cjkrS5vJSKicMxb62W2cK9e5I62x+paAQDaDAznvqNFMBXZy/S8t9sqh0CL5ww4+pDXhA9PCdob7EOSA9e4EzgXTMiyyU8Z7gqSqq9DwH4fxiENJLzGbD2e+VM9iPQqp0gI9/4Xn1ZX1x12ddFenAYkLjIZCf8BBAJZRq5WeTwr1B
127.0.0.1 ssh-dss AAAAB3NzaC1kc3MAAACBANS+fcEeUJYXUH+58diSH8FsHQlj/3xjSVmEf5Od2ip87ro6ZSn3nJI1RR+ALqcLGn/K9fccl4Bj4Oq+M/6iMIL7ZQ6cAwzox9E0w0AjwQg+17WjWIfQNhycnuCCLcg6ThVobZ30RrNFcmwcXKKXP2CRS+eT6Ex8wC42uOEfMvQfAAAAFQDJYtWp9ZaxF1Ej/H0uu8Sqx+9dkQAAAIEAtrLXsPDqCvRwnGtusl1rlzjJCHYMJFZ5eAFDRCdNNUpGqHaHZpw9v8OIt6Qtvx6eVn97opVJ71FG9Xxpl17sIegh8/gprZZlK8ct9Lfs2YFOxcXv+i2r1dVHZwUkwSiYUE59Af71d+Os9VNStTj/U/GXtVNMS7NyqKoaWfFlItgAAACAevPvahBRDZbsjcfhf736q5vyEZbHau5s3VfSQci1u0rIekDhymTyul3KwM7aOFq3f9Y0SfMFKTfQJq45yYCMFZcwnvJSqDdUZVHffKcGcyj3N3mnIGMiU/3mbKH+xbCPn8f+HURembC9S4X+wtPHTHqhCWj2LAUDOgzdSvJ/C9o= root@squeeze
localhost ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzupGWlTD1QFcjkNoqyWuAMBo386WHH+B/EVs1pNYBd8NrHvTvFeuvDxOBwIYkI4T7ak0wXLtbW9o0KV2EPtrlGwMelVbM+X4nxXrXtDk5B6Zl0tcPu1NLwHRwhzh8reNXuEqLHE5EfPM1Z8B1eYNoiMEXdCXKzb8dlDXgIe/cjkrS5vJSKicMxb62W2cK9e5I62x+paAQDaDAznvqNFMBXZy/S8t9sqh0CL5ww4+pDXhA9PCdob7EOSA9e4EzgXTMiyyU8Z7gqSqq9DwH4fxiENJLzGbD2e+VM9iPQqp0gI9/4Xn1ZX1x12ddFenAYkLjIZCf8BBAJZRq5WeTwr1B
[notice utserv.c] *** save and disease test: 
[info serverTree.c] Serializing the server tree file: stdout
# This file is managed by MediaTeX software.
# MediaTeX mdtx2-coll1@127.0.0.1:22 servers list:

master     6b18ed0194b0fbadd08e0a13cccda00e
collKey    1234567890abcdef

# score parameters
uploadTTL  1 Month
serverTTL  2 Week
suppTTL    5 Year
maxScore   10.00
badScore   1.00
powSupp    2.00
factSupp   2.00
fileScore  10.00
minGeoDup  2

Server 6b18ed0194b0fbadd08e0a13cccda00e
	comment   "this is server2"
	label     mdtx2
	host      127.0.0.1
	lastCommit 2010-01-01,01:00:00 
	mdtxPort  6560
	sshPort   22
	wwwPort   443
	networks  private, www
	gateways  private
	cacheSize 200 Mo
	cacheTTL  1 Month
	queryTTL  2 Week
	provide	  022a34b2f9b893fba5774237e1aa80ea:24075=7.50,
		  de5008799752552b7963a2670dc5eb18:391168=10.00
#	keys:
	userKey   "ssh-dss AAAAB3NzaC1kc3MAAACBANTUb46yvsV3bL8AX7oSg48oyN2MPqVCLWL8GiGADVzX71dZmYiqFeTJ5v3vBgk/7rEiaUzfAIZ0ebXhKB1TSc17Vqbdx2DfHm3/IbgBgrBe47VAkbPX+iW2n1zC9fBY5bc/819V0Szf7qvUyzZUkJ/9Vsi79Ikbq7rWu8r3VBeVAAAAFQDTyYPXMe1NzSrUHagG4BLlEQEx7QAAAIEAmYWtuhy0uuoLsoZu96ECnD6Se+buik4WhEi6xuAMPe+/RR7z3IHTh7Xvg56PyfqlFNReFnlc1s23ZZMmWsSAtNYFWqGrir/rddfisDm9Esk5aqPuwi8ToEFikGpthbJZYHjz4PpB2jfWDyLax2HpzFx4vmd1LcrCCM5PtuJ1sEAAAACBALPb55K2CZT3etbLgJ0rfoYDMnutNl38kK5rxf5Ps7Qfq2Uayv1BSKh8arOoMi94qoGKmBDLmwy99raNL4UhVly6YcnOPZ1yhVMfSGy2B1bFHIxh4qhxulm6VsVcPxIQpfwjQCRPImo57jkIjVk49o+K6DY7pDuy60MOmkXPr/sC mdtx@host"
	hostKey   "ssh-dss AAAAB3NzaC1kc3MAAACBANS+fcEeUJYXUH+58diSH8FsHQlj/3xjSVmEf5Od2ip87ro6ZSn3nJI1RR+ALqcLGn/K9fccl4Bj4Oq+M/6iMIL7ZQ6cAwzox9E0w0AjwQg+17WjWIfQNhycnuCCLcg6ThVobZ30RrNFcmwcXKKXP2CRS+eT6Ex8wC42uOEfMvQfAAAAFQDJYtWp9ZaxF1Ej/H0uu8Sqx+9dkQAAAIEAtrLXsPDqCvRwnGtusl1rlzjJCHYMJFZ5eAFDRCdNNUpGqHaHZpw9v8OIt6Qtvx6eVn97opVJ71FG9Xxpl17sIegh8/gprZZlK8ct9Lfs2YFOxcXv+i2r1dVHZwUkwSiYUE59Af71d+Os9VNStTj/U/GXtVNMS7NyqKoaWfFlItgAAACAevPvahBRDZbsjcfhf736q5vyEZbHau5s3VfSQci1u0rIekDhymTyul3KwM7aOFq3f9Y0SfMFKTfQJq45yYCMFZcwnvJSqDdUZVHffKcGcyj3N3mnIGMiU/3mbKH+xbCPn8f+HURembC9S4X+wtPHTHqhCWj2LAUDOgzdSvJ/C9o= root@squeeze"
end

Server 746d6ceeb76e05cfa2dea92a1c5753cd
	comment   "host1.mediatex.org configuration file"
	label     mdtx1
	host      localhost
	lastCommit 2010-01-01,01:00:00 
	mdtxPort  6560
	sshPort   22
	wwwPort   443
	networks  www
	cacheSize 100 Mo
	cacheTTL  15 Day
	queryTTL  1 Week
	provide	  022a34b2f9b893fba5774237e1aa80ea:24075=0.00,
		  0a7ecd447ef2acb3b5c6e4c550e6636f:374784=10.00,
		  de5008799752552b7963a2670dc5eb18:391168=0.33
#	keys:
	userKey   "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDlnF3vIn3ad3kMTMdqLa/Q7WK0F2Lm1LbUPTh58ZYcCevtB0Eh4nyEuglApyu0d44/PfcUBAUEBVn3TOwPH6PIU0s7UmiiZpNHSO1cRWuULts8ebE2ePPbKiNj8rcqmTTuoxXB3nnbWtbqJAu4ld6s1P5Rtm84B53dltlkZijCbtBa3FFPpShiRJQ8mIdQBKn5GXg5FDZ6xj9DUVcWAYxmkZXH3Wa2Uy1fSGMhhvSkvzDWJI/m3bBcQQZVJzrrr3Z+KG4MxO2qe1IhOa5Vjlf20PdRy0oB25NU09OfeV+LhfEdDadWvf2lRvcR60RhAf9C4GJOtRSjpO2xo8FNBnjB"
	hostKey   "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzupGWlTD1QFcjkNoqyWuAMBo386WHH+B/EVs1pNYBd8NrHvTvFeuvDxOBwIYkI4T7ak0wXLtbW9o0KV2EPtrlGwMelVbM+X4nxXrXtDk5B6Zl0tcPu1NLwHRwhzh8reNXuEqLHE5EfPM1Z8B1eYNoiMEXdCXKzb8dlDXgIe/cjkrS5vJSKicMxb62W2cK9e5I62x+paAQDaDAznvqNFMBXZy/S8t9sqh0CL5ww4+pDXhA9PCdob7EOSA9e4EzgXTMiyyU8Z7gqSqq9DwH4fxiENJLzGbD2e+VM9iPQqp0gI9/4Xn1ZX1x12ddFenAYkLjIZCf8BBAJZRq5WeTwr1B"
end

Server bedac32422739d7eced624ba20f5912e
	lastCommit 1970-01-01,01:00:00 
#	keys:
	userKey   "ssh-dss AAAAB3NzaC1kc3MAAACBALSNj2g79yICAQHQBrEWzwYp/h7KGJl7KPOkRcgyr1vyBhBYfJJQpxhKZOBLkFs4RoyZmx+NX3tMUNH2FkYPbSWjms1czokhM9nq96ZUGCx/rWZ2oDB5KVNx+sp8rqveTDB45FTfJQ6+2PDoHfajc6kthxM/UUTBzTLaTD5V1ChjAAAAFQCfhKdnRBlZEnyp5U4w+xqJLg/yPwAAAIEAp6SRRiF6ucA+NZ+GxsBBgQMKT/uokI7rxWnljPeyVbAi3c07mdpEoLUDAUbAy4qfatWXEf9RDLGQuFwyMeBkMtRHENmuWyIlRT191xhQzKMAhbFukRNdmjm7lvB9gnlhPiESxmrZqBppeKh13CtntWQyEL8KYv5AVoEwfkwGyGMAAACAAW8BloIq4V7j4/qEJWjvlHUbVHlgeZU9gnOSL2BDaS1zqTYrUTuWo/HKRMWf6xWbh1Es7YpYtQ8EA8Z/fW4xGSH1J+nhCNxepezXNAzejPF/aHph9YcPp7n6qdW0dHoL6GfPJt47Rs+XyXalEiyNU1POm38qn3/BKuHisS49/0o="
end

# Local Variables:
# mode: conf
# mode: font-lock
# End:
[info openClose.c] steps: 0 / 0
[info openClose.c] callCommit mdtx1-coll1: 
[info confTree.c] free configuration
[info utserv.c] exit on success
=================================
  Second run 
=================================
[info serv.c] client ipc key: {LOCALSTATEDIR/cache/mediatex/mdtx1/cvs/mdtx1/mdtx1.conf, 6562}
[err serv.c] cannot take concurent access as it is already locked
[err serv.c] fails to get writter lock
[info confTree.c] free configuration
[info utserv.c] exit on error
