[notice supportFile.y] parse supports
[notice confFile.y] parse configuration
[info openClose.c] estimate 125 steps for load
[info openClose.c] parse coll1 collection (5SXC)
[info openClose.c] load coll1 records
[notice recordList.y] parse record list
[info openClose.c] steps: 0 / 0
[notice cacheTree.c] we only record one local supply by archive
[info openClose.c] steps: 0 / 0
[info openClose.c] exit on success
